### ISSUE TITLE
RTMP/Live Streams on Boxee Box

### ISSUE THREAD

**Issue by Taj786** [boxeehacks/boxeehack#100]
Can we kindly get RTMP streams to work or be playable on boxee box. This feature has been long time coming and I'm sure tons of boxee box fans would love to have this feature implemented. RTMP and live streams work great XBMC, so I can't find a reason why it cannot on boxee box. Thanks.

**Comment by boxeehacks** [comment]
Unfortunately it's not possible to change anything on the basic playback side of Boxee Box and add new formats and types of streaming.
