### ISSUE TITLE
Option to open Spotify from Music shortcut on homescreen

### ISSUE THREAD

**Issue by hessius** [boxeehacks/boxeehack#105]
I've never had any music on my NAS / Boxee simply because it's more of a hassle than using spotify. Having the music shortcut on the homescreen is fantastic though, but would it be possible to add an option to simply change the behaviour of the music button on the homescreen so that it opens spotify (or Rdio etc)

**Comment by scottybgoode** [comment]
I second this. Would never store my mp3s on boxee storage, but would use the my music button if it routed straight to spotify or some other music choice. Or an option to just hide the my music channel. 

Thanks

**Comment by hessius** [comment]
I've fixed this, will make a pull request soon

**Comment by boxeehacks** [comment]
Pulled in this request. Will make it to the next release.
