### ISSUE TITLE
Click back for quick clock

### ISSUE THREAD

**Issue by SiIason** [boxeehacks/boxeehack#106]
Following on from issue "Add Clock on Movie Page"

Add a clock to the 'do you want to exit/leave' popup that shows when you press the back button from a show/movie/app/etc. Finding the time atm is a real hassle in boxee you have to stop everything :/

**Comment by boxeehacks** [comment]
Would be better as part of the OSD

**Comment by boxeehacks** [comment]
Actually you don't. You can just press the center button on your remote. That will bring up the On Screen Display (OSD) which has a clock in the top right. You don't even have to stop playing the video.

So won't add this... since a better way is already part of standard Boxee...
