### ISSUE TITLE
Improve airplay

### ISSUE THREAD

**Issue by medicineuk** [boxeehacks/boxeehack#107]
I would love to see the airplay side of Boxee improved so that all videos from iPad apps worked correct. At the moment if I try and stream from iPlayer or 4OD (both UK services but I'm sure the same is true of US) I just get sound no video. It would also be really nice if I could airplay/ screenshare my Mac desktop like I can on my Apple TV.

**Comment by hessius** [comment]
Unfortunately not possible atm. Please see #57 and #62
