### ISSUE TITLE
Recently Added Not Showing

### ISSUE THREAD

**Issue by Deoxizn** [boxeehacks/boxeehack#120]
after a reboot of the boxee after adding recently added itll show all the tv shows/movies but once i reboot the box it just shows up blank from there for on even after adding new content til re-selected.

**Comment by boxeehacks** [comment]
Will look into this...

**Comment by boxeehacks** [comment]
Hmmm.... tested this quite extensively, but I cannot get this behaviour reproduced. Closing it for now, but feel free to comment if you have any additional info to share, and if I can get the behaviour here I'll re-open.

What I did to test was:
- factory restore
- install the hack
- add my movie source again over SMB
- went into settings and changed the home content to recently added
- went to home, recent movies were there
- rebooted, recent movies were still there
- shut off the device, turned it on again, recent movies were still there
