### ISSUE TITLE
Remove unwanted menu items. 

### ISSUE THREAD

**Issue by scottybgoode** [boxeehacks/boxeehack#126]
I would like to have a feature to hide or remove the MUSIC and WEB channels from the home screen. I never use my tv to listen to an mp3 collection (surround sound stereo for that) and I never use the slow Boxee Browser (plus there is still a browser app in the app section). 

Where can I go to hide these two sections from displaying on the main menu?

**Comment by boxeehacks** [comment]
This is in 1.3.5 :)
