### ISSUE TITLE
Shortcut to Boxee built in weather

### ISSUE THREAD

**Issue by scottybgoode** [boxeehacks/boxeehack#127]
Boxee has a great built in weather feature that is accessible through the settings menu. I know you can also download a weather app. I would love to be able to have a weather icon on homepage or nearby so i could get forecasts instantaneously in the morning. 

I use boxee box for movies and videos at night and first thing in the morning for the live TV and could use the weather functionality.

**Comment by boxeehacks** [comment]
There is already a weather icon on the home. Maybe we could turn that into a button. Will look into it...

**Comment by boxeehacks** [comment]
This will be in the new release (1.4.0).
