### ISSUE TITLE
use movie outline instead of overview in list view

### ISSUE THREAD

**Issue by tennisbgc** [boxeehacks/boxeehack#130]
When in the movie index page in list view the movie overview is displayed and I'd really prefer the outline displayed there and the overview displayed in the details page.

**Comment by boxeehacks** [comment]
Just curious, but why would you want this? (All of my content only has the overview, so I don't have any way of seeing  what the benefit could be... :) )

**Comment by boxeehacks** [comment]
Closing because no feedback...
