### ISSUE TITLE
Support for Amazon Video on Demand

### ISSUE THREAD

**Issue by odedia** [boxeehacks/boxeehack#134]
It would be great if we could get a way to watch Amazon video on demand on the boxee box. RIght now it's not possible, Amazon identifies the website as unsupported. An app would ofcourse be a great option if possible.

**Comment by boxeehacks** [comment]
Unfortunately it's not possible for us to modify the browser and the way it identifies itself. This would have to be done through an app, if possible. Maybe someone in the developers section for boxee applications has an idea or can help?

http://forums.boxee.tv/forumdisplay.php?f=19

**Comment by odedia** [comment]
Too bad... I wish we had other browser alternatives as apps. How hard will it be to make a third party app from the webkit source code? I guess not simple.

Do you believe airplay _mirroring_ will be possible? that should partly solve the problem.

Thanks.

**Comment by boxeehacks** [comment]
Unfortunately no :( ... anything that displays something on the screen needs to go through the Boxee executable. Anything that adds substantial new features (a new streaming protocol, a new rendering engine for webpages, a new way structure to the library, etc.) requires recompiling the Boxee executable. However we can unfortunately not do this because of missing parts of the Boxee source code (the Intel SDK which is needed)...

**Comment by dembonez** [comment]
I wonder if the boxee browser app files are available somewhere... a secondary thought would be to mod the config in the app, and host it on a 3rd paryt repository, (even local; not hard to do).

Of course, if app development requires access to boxee's missing source code, I guess we're sunk until that gets sorted out.

**Comment by boxeehacks** [comment]
The browser "app" only does one thing, and that is start the browser functionality that's built into the Boxee executable. So without modifying the Boxee executable there's no point in modifying the app files, except for things like starting up with a different homepage...

**Comment by odedia** [comment]
I'm wondering if there is any way to really go further than the current limitations with the Intel SDK.

This conversation implies that Intel must release the SDK or at least something workable to the public due to GPL licensing:

http://software.intel.com/en-us/forums/topic/266663

I wonder if there's a way to get it or not. We already have some source code of Boxee, although very old. And it is ofcourse possible to then go the route of XMBC or Plex or other open source alternatives.
