### ISSUE TITLE
Wrong rate in new script Subtitles for TV

### ISSUE THREAD

**Issue by ducapedia** [boxeehacks/boxeehack#135]
The new language filter, works fine, but there is something wrong with ... I don't know what.
I already used "periscope" and "subliminal" in my dd-wrt router, and I never get this.
When I search for a sitcom subtitle (tv show), the results shows in the list only subtitles for this show (ultil here.. fine), and filtered only by languages I checked (ok them)... but, showing anothers episodes (and seasons) in the list... and worst.. with high rating in front (like 83% and above others in same episode and season).
I presume that script comparing the whole name, and rating by matching quality, groups... but, the episode and season its mandatory.
Return in list another episode is bad as showing subtitles from another tv show. (filtered in tvshow, season and episode and language, rated by the others elements, like video quality and group).

**Comment by ducapedia** [comment]
no one did notice this ?

**Comment by michske86** [comment]
I have noticed that the subtitle system gives me wrong season/episode options too from time to time, but most of the time they get <50% while the one i'm looking for is popping up on top. I can perfectly pick the top one, being the most correct one usually, without being bothered by the faulty ones. In my opinion it's better to have too many results (with the less correct ones near the bottom) than tightening the search more and thereby perhaps losing some of the correct ones... :)

**Comment by ducapedia** [comment]
I agree.. and I reported in a intent to help and test.
In some case (not ever) the wrong episode was above of the correct ones.
And another reason on my consern is ... I dont understend why this occur..

**Comment by boxeehacks** [comment]
The last release was missing hash-comparison functionality. This has been added to the new version which should improve reliability. As of version 1.4.0
