### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by ducapedia** [boxeehacks/boxeehack#139]
FTP can't access /media folder (to send downloaded videos directly to boxee hard drive)
(without this, I can't see another reason for ftp server)

**Comment by boxeehacks** [comment]
The reason for the FTP was mainly to get at the Boxee "internals". But we can easily additionally add the mount point to the FTP access so you could also access your attached drives...

**Comment by boxeehacks** [comment]
Access to the media folder has been added to the development branch and will be in the next release
