### ISSUE TITLE
Check functionality of Scan folder Icon

### ISSUE THREAD

**Issue by Silent337** [boxeehacks/boxeehack#140]
A while back I submitted a request to fix an issue with the "Scan for new files in this folder" button on Boxee. As per their usual motives, it was closed and ignored. Can you have a look at the functionality behind that icon and see if there is a way to make it active? Thx

![Boxee Scan.jpg](https://f.cloud.github.com/assets/2942949/2166/76ab2b0a-41a6-11e2-92e1-4a2dd4324f4a.jpg)

**Comment by boxeehacks** [comment]
This button isn't a "scan current folder" button, but it's a "rescan your library" button and has nothing to do with the current folder you are in. This behaviour is hardcoded in the Boxee executable, and unfortunately is something we can do nothing about...

**Comment by Silent337** [comment]
Thanks. Surprisingly I was told by one of the dev team through JIRA that this was a scan local folder function. Lovely that they don't even know their own product. :)
