### ISSUE TITLE
Scan wdtv created folders for fanart/backdrop

### ISSUE THREAD

**Issue by ghostyroasty** [boxeehacks/boxeehack#142]
It would be nice if Boxee+ would look for backdrops added by my Wdtv Live. The format is if there is a folder created already for a film is adds a subfolder.

If there is no folder for a film then the wdtv created a folder in the root directory. Both folders are in the same format: ".moviefilename.backdrop" The backdrops are then named "backdrop00.jpg" and so forth. There are "filename.metathumb" files created as well.

**Comment by boxeehacks** [comment]
Isn't there an option to tell WDtv Live to follow a different structure with its backdrops? The way it is done in Boxee+ right now is pretty standardised with various HTPC systems, so it doesn't make much sense to change this for one specific system.

Could be an option in the settings, but don't want to add thousands of settings for things that can be fixed better by setting up the wdtv live in this case.

**Comment by boxeehacks** [comment]
Will possibly reopen if there is a lot of demand for this, and at least some feedback is given on whether there is no other possibility when using Wdtv Live
