### ISSUE TITLE
pyLoad

### ISSUE THREAD

**Issue by kellekellner** [boxeehacks/boxeehack#146]
What's about pyLoad. Is is possible to add it?

http://pyload.org/de:start

It's a download manager for One-Click-Hoster.

**Comment by boxeehacks** [comment]
This is something that would typically be used in an app to play back videos on such networks. I think Navi-X does something quite similar actually.

Without connecting quite some functionality around this, just having such a loader doesn't make much sense. Good to know such an option exists though if it becomes relevant in the future. For now this isn't something I'll be looking at integrating though.
