### ISSUE TITLE
Live TV support for NTSC Channels

### ISSUE THREAD

**Issue by dclark10** [boxeehacks/boxeehack#154]
Boxee chose to not support NTSC cables channels (analog) only the digital clear QAM channels. The tuner however supports NTSC.  It would be nice if we could have the ability to view the NTSC channels with guide data. Depending on your cable company that would increase the live tv channels from about 15 to about 60.

**Comment by boxeehacks** [comment]
This is not possible, since it requires modifying the Boxee executable itself, which we don't have access to.
