### ISSUE TITLE
Problems with the recognition of Hard Disk connected to Boxee via USB with version 1.3.1-1.3.5.

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#156]
Is there a problem with the automatic detection of hard drive connected to the Boxee from version 1.3.1. to the last. Next update, If I call a movie from my movies library on the hard drive connected, the Boxee does not seem to recognize the HD and then crashes. To restore all I have to unplug the HD power cord and reconnect it.

You can take a look please?

**Comment by dmike3** [comment]
This is a very odd issue. If you disable the hack does it start working fine?

**Comment by saragusa** [comment]
I'll look and let you know ....
