### ISSUE TITLE
update deletes boxee+

### ISSUE THREAD

**Issue by swetoast** [boxeehacks/boxeehack#157]
Hi found a little issue 

im using a sd card to update boxee+ and when i press check for update then ok it reboots and tries to update boxee+ but when it starts up again boxee+ is gone 

not sure if its me doing it wrong or if there is a bug but i thought its worth while to report it in anyways

Regards
Peter

**Comment by vincentmac** [comment]
I just ran into this problem too.

**Comment by skipperbent** [comment]
Same her... it deleted the Boxee plus - when installing Boxee plus again it kept getting black screen on restart until i removed the USB from the Boxee box - and Boxee+ was back!

**Comment by swetoast** [comment]
Had to run the debug.sh file before mine bumped back

**Comment by boxeehacks** [comment]
This should be fixed with the next update
