### ISSUE TITLE
Improving Media Flags.

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#158]
The Media Flags are still a lot of improvement (definition - SD, HD, 720p, 516i, 1080p - video content - mkv, mpeg4, avi-, film genre, etc.).

Can anything be done?

**Comment by boxeehacks** [comment]
According to Boxee documentation that info _should_ be available. However in reality it isn't :(

Unfortunately there is nothing I can really do about this. So for now the studio label is the only thing I could reliably get out of it...
