### ISSUE TITLE
Auto force aspect ratio videos that are 4:3 to 16:9.

### ISSUE THREAD

**Issue by Baek87** [boxeehacks/boxeehack#16]
Make a setting that allows you to Auto force aspect ratio videos that are 4:3 to 16:9.

**Comment by boxeehacks** [comment]
You can already set the aspect ratio in the video settings and then tell it to make the settings default for everything. That said, you really shouldn't do this, it makes everyone look fat ;)

**Comment by Baek87** [comment]
Haha yeah thats true! :-) i didn't realize i was there allready! Thanks for you great piece of work!
