### ISSUE TITLE
Some Bugs in 1.3.3

### ISSUE THREAD

**Issue by ducapedia** [boxeehacks/boxeehack#169]
I cant see Boxee in my network, but when I click in it, I cant acess (pop up erros say something about samba credentials, but I've tried "guest" and none..)
FTP acess works fine, and I can see now /media (thanks), but, when I enter in this folder, I see subfolders like hard drive UUID (instead label of that)... and when I enter ... are empty.
The same for subfolders NFS and UPnP.
WebGUI doesnt work..the right IP and door, but shows up a page with error (not webgui) sayng that was not possible to start webserver.

**Comment by boxeehacks** [comment]
Please make separate issues for each issue that you're having. These kinds of combined issues are not easily manageable...

Please also make sure you're using the latest version (which is 1.3.5) while testing.

FTP is a known issue (#198)
Accessing the network happens for some people, but should always still be accessible directly via IP-address.. e.g. \192.168.2.8\whatever ...
WebGUI doesn't work? There is no such feature ... what do you mean by "door" ?

**Comment by ducapedia** [comment]
Sorry.. door and port means the same thing in my language.
