### ISSUE TITLE
bigger movie posters.

### ISSUE THREAD

**Issue by urpick27** [boxeehacks/boxeehack#173]
the option for the smaller view mode was cool. I'd also love the option for a larger view mode, like 4 posters per row.
![912boxee moviese](https://f.cloud.github.com/assets/2975970/5396/3fc19554-4375-11e2-8042-084efdc32743.jpg)

**Comment by boxeehacks** [comment]
If you are into big art and showing the movie in the most ideal way possible. Look forward to 1.4 ;)
I like this as well though, so maybe as well. Though I don't want to get XBMC syndrome where you have 24 different view styles you have to cycle through to get the one you want. Let me think about that...

**Comment by daver77** [comment]
I'd like this too, I use BoxeeBox on a 26" TV in the bedroom so the images are sometimes hard to see. Not sure on your limitations but can we go a step further and lose that left bar?

**Comment by jesseblue** [comment]
i smell a new view in 1.4...like the home page but everytime you scroll the fan art shows on the background...ooh...so excited...

**Comment by daver77** [comment]
you mean show fan art as each cover is selected? can't see the point, the covers would cover most of the screen so you won't see the fan art and I can't see it being good for performance. 

Unless we have an XBMC carousel type view, i'm with keeping it simple though!

**Comment by jesseblue** [comment]
to each their own...i like the option of seeing fan art when scrolling through my movie lost...i don't care much about imdb rating / rotten tomatoes or even plot...

**Comment by F33db3ck** [comment]
Movie posters are loading slow, 130+ movies, bug or caching problem?

**Comment by boxeehacks** [comment]
@F33db3ck check issue #190 which is about this issue.

**Comment by boxeehacks** [comment]
For now not adding new view modes. I think the new viewmode in 1.4.0 will satisfy people who are into bigger art enough.
