### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by kellekellner** [boxeehacks/boxeehack#174]
What's about banner at Series?

**Comment by boxeehacks** [comment]
What do you mean exactly?

**Comment by daver77** [comment]
http://wiki.xbmc.org/index.php?title=Wide_banner_icons

Probably this, might be a nice option, I use banners on my XBMC for TV Shows

**Comment by kellekellner** [comment]
Yes, Instead of the posters.

**Comment by boxeehacks** [comment]
Duplicates #206
