### ISSUE TITLE
Request: Viewing Movie Clip Files in Photo Section

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#175]
Like many people I have many short home movie clips stored alongside my photos. My photo folders are never scanned, so the only way to view them is via the files menu option.

However, it would be nicer if the movie clips could be viewed at the same time as viewing photos. (as they are stored in the same folder as photos of the same family events).

Unfortunately today, if you select Photos and then view the folders, it filters out all media which does not have a picture extension such as .jpeg, and hence does not show you the movies.

Is this possible to correct?

**Comment by boxeehacks** [comment]
This one's easy. Go into the "File Sources" settings menu, select your pictures file source and change the Media Type to "Video" and Type Of Scanning to "Never". Everything photo related stays the same (as far as I can tell) but now it'll also show videos.

**Comment by LewisFamily01** [comment]
But then, if you select "Photos" from the menus, you won't get shown the Photo sources as there would be no Photo sources.

So for instance if we managed to get Photos back on the home page, it would make that option pretty useless.

Its a big shame the boxee isnt geared up to view this sort of media, its not like we would scan it and have it index in a library and manually create NFOs for each 10 second clip is it.
