### ISSUE TITLE
Request: Viewing Movie Clip Files in Slideshow Screensaver

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#177]
When using the photo screensaver, it picks at random photos from the specified folder (and subfolders). This is great.

However, could this be expanded into a more multi-media screensaver, that could play at random any MEDIA file in the specified folder. e.g. if it finds a movie clip it plays that, or even if it finds a music track it plays that?

Is this possible?

**Comment by boxeehacks** [comment]
Unfortunately this is not something we can fix :(
