### ISSUE TITLE
Request: Manual Rescan in File just re-scans selected folder

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#179]
Today when selecting manual re-scan, it appears to rescan all sources, and takes ages before the new media is visible.

It would be good if in FILES a rescan only rescan's the selected folder (and subfolders).
If in TV, it only rescans the sources where TV episodes have previously been found
If in MOVIES, it only rescans the sources where MOVIE episodes have previously been found

Of course automatic rescans of sources should check for any media type across the whole of the source. 

The idea is to make manual re-scans quicker, by reducing the scope to what is probably wanted by the user when he/she requests the re-scan.

Is this possible?

**Comment by boxeehacks** [comment]
Unfortunately this is not possible. We cannot even set a specific source to refresh. The Boxee Box only has two commands:
- UpdateLibrary(video)
- UpdateLibrary(music)

Which is pretty crap, but unfortunately nothing we can do about this.
