### ISSUE TITLE
Side Note: Kill Mandatory Update in Older Boxee Builds.

### ISSUE THREAD

**Issue by urpick27** [boxeehacks/boxeehack#181]
I really loved the look and feel of the 1.2.2.20482 build, but I can't keep it unless i disconnect from the internet which takes away almost all of its functionality. I don't know if its possible but could you modify older builds to remove the mandatory update?

**Comment by war59312** [comment]
Well for now you can block the updates using squid.

See: http://forums.boxee.tv/showthread.php?t=35225&page=9&p=268020#post268020

Also, see this script: https://github.com/jskov/boxee-version-restorer

**Comment by urpick27** [comment]
thnx mate. I'll try that.

**Comment by urpick27** [comment]
Attempting the boxee-version-restorer.  I'm at the z-prep.sh part and have no clue how to follow the instructions. Can someone please help me?

**Comment by boxeehacks** [comment]
It's already quite a lot of effort making sure these builds work properly with just one version. I don't think it'll be feasible for me to maintain a version for the older ones.

However the same techniques will apply. What you can do is fork this project, and use the same installers etc.
Then just remove our custom 720p folder and copy in the one from your 1.2.2 firmware and start modifying from there. Probably a lot of things can just be copied from this version, or easily adapted if you're a bit handy with XML and shell scripts.
