### ISSUE TITLE
Install doc update

### ISSUE THREAD

**Issue by nhinze** [boxeehacks/boxeehack#186]
The installation instructions on www.boxeeplus.com should say to re-enable Windows File Sharing after installing Boxee+. My install of 1.3.4 added the correct hostname, but disabled Window File Sharing. Boxee+ only worked when I re-enabled it and restarted the box.

**Comment by boxeehacks** [comment]
It shouldn't be needed to re-enable. If you do it in the correct order (first enable, then enter the hack string) it should stick. I've only ever had it not work if I did it the other way around.

That you have to do that _IS_ on the FAQ though.

This can probably be made clearer though... Will look into this

**Comment by boxeehacks** [comment]
Clarified this on boxeeplus.com
