### ISSUE TITLE
More home screen customisations (APPS!)

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#188]
Make it possible to replace certain icons with apps
- Spotify
- Netflix
  ... etc ...

**Comment by daver77** [comment]
Awesome, I was thinking something like having x options (say 3) in the boxee+ options page and in each of these 3 options you can choose one of you apps or browser favourites to add to the homescreen.

This would be great for us in the UK as we have alot of catch up websites that work on Boxee but don't have an app

**Comment by boxeehacks** [comment]
This is in 1.4.0
