### ISSUE TITLE
Request: More options on the homepage lower section

### ISSUE THREAD

**Issue by daver77** [boxeehacks/boxeehack#189]
The latest additions option for the lower part of the homescreen is great, i'd like to see some extra options along the lines of 'latest movies/shows only' etc, basically for my persoanl preference I don't want to see music updates

maybe something like this will cover everyone
latest all (eg as we have now)
latest movies
latest shows
latest movies/shows
latest photos
latest music

**Comment by boxeehacks** [comment]
Added a new "fanart" option, which actually disables the bottom area and makes the home screen a full-screen fanart display randomiser

**Comment by boxeehacks** [comment]
Other stuff will be future stuff...
