### ISSUE TITLE
1.1.0 not updating to later version

### ISSUE THREAD

**Issue by RoRoo1977** [boxeehacks/boxeehack#192]
Running 1.1.0 on my boxeebox.

When i go into the boxeeplus settings and check for update it claims to have an update, but when I select OK, nothing happens.

Is it possible to manually update using telnet? What are the steps?

Thanks

**Comment by d4yz** [comment]
Version 1.1 doesnt have an auto updater. youll have to download the new version and run the install.sh again

**Comment by boxeehacks** [comment]
Updater was a 1.2.2 feature, so this is expected behaviour :)

**Comment by RoRoo1977** [comment]
Excellent :) Thanks for responding
