### ISSUE TITLE
The subtitles search don't work

### ISSUE THREAD

**Issue by theofonseca** [boxeehacks/boxeehack#193]
guys when i try to search a subtitle online always my boxee jams and resets. i already try to unchek de subtiltes hack but same thing. everyone has experienced something like this?

**Comment by boxeehacks** [comment]
Have you tried removing Boxee+ and re-installing? Maybe something went wrong with the initial install?

**Comment by theofonseca** [comment]
yes, i tried. it's inconsistent, sometimes works, sometimes don't. I'm thinking in clear all settings and build my library from zero again, maybe it can fix the problem. cause when i unistal the hack the subtitles still messed up.

**Comment by boxeehacks** [comment]
Hmmm... that sounds like a Boxee issue then, because after an uninstall no trace of Boxee+ is left, so it must be core Boxee stuff failing.

One thing you could try is doing a factory restore and see if the issue still remains.

**Comment by theofonseca** [comment]
Yep, i'll try this. Thanks man!

**Comment by boxeehacks** [comment]
Good luck ;)

**Comment by boxeehacks** [comment]
Also was an issue with a pull from jerbob92 that wasn't included in the latest build properly. That will be in 1.4.0
