### ISSUE TITLE
FTP issue

### ISSUE THREAD

**Issue by ducapedia** [boxeehacks/boxeehack#198]
FTP is now mapped to see "/media" folder (thanks)
But inside this folders, does not show a subfolder called "boxeehd" or the label of HDD partition.. I can see a sub folder wit UUID of the partition as naem.. but inside it, theres nothing...
I guess thereis no permission to follow symbolic link ?

**Comment by cacildo** [comment]
I really wish i could access the hdd i use on the Boxee box using FTP. It could really easy it up for me.

**Comment by boxeehacks** [comment]
The only way to fix this turned out to be to give access to the root. Updated in 1.4.0
