### ISSUE TITLE
Add new VPN shortcut in the main browser section. 

### ISSUE THREAD

**Issue by dmike3** [boxeehacks/boxeehack#20]
In the Back pop up menu just next to the settings to add a VPN icon.

**Comment by boxeehacks** [comment]
And what should it do exactly? Once you setup the VPN you don't ever have a reason to touch it again right?

**Comment by dmike3** [comment]
My suggestion is just a shortcut of connecting and disconnecting from this menu. So for instance it's grey once there is no VPN connection and than colored when its connected.

**Comment by boxeehacks** [comment]
Ok... clear. Just trying to understand the use case though; why not just leave it connected? Why would you disconnect?

**Comment by boxeehacks** [comment]
Reason I'm asking is because it will be a LOT of work to get done, since we don't have direct access to this kind of functionality, and working around that is really tricky. So if there is a better solution (like using the vpn always) then that's a much much better way to go forward.

**Comment by dmike3** [comment]
I'd like to have options of my current region and the options of VPN. I do this now, but I have do dig through menus. It would be much easier if the option was right at the main screen to connect instead of going through all the sub menus.

**Comment by boxeehacks** [comment]
Moving discussion to #88
