### ISSUE TITLE
Default Aspect Ratio change Feature Request

### ISSUE THREAD

**Issue by Mike120** [boxeehacks/boxeehack#200]
Not sure if this is possible but it would be good if you could have all videos play in an aspect ratio of your choice. For example an older tv show with a 4:3 aspect ratio play in 16:9.

**Comment by jesseblue** [comment]
it can be as simple as pressing the 'z' button to o through the different ratios

**Comment by Mike120** [comment]
Yeah I know how to do it, It just gets annoying if you're watching a lot of episodes from a show that's in 4:3. Would be better to just have it auto change when it starts

**Comment by boxeehacks** [comment]
Duplicate (sort of) of #119 

Though you really shouldn't stretch 4:3 to 16:9. It looks really _really_ ugly, and makes everything look wrong and distorted ;)
