### ISSUE TITLE
subtitle plugin overide

### ISSUE THREAD

**Issue by Raboo** [boxeehacks/boxeehack#203]
As I see, there are two problems with the subtitle plugin.

The subtitle plugin turns itself on mostly even if i turn it off(even if i disable boxee+).
The subtitle plugin disables choosing of integrated subtitles in mkv files, which is kind of bad since not all subtitles it downloads are good.

**Comment by Raboo** [comment]
It could me that the subtitles plugin has come persistent somehow..
It not mounted and it can't be deleted.

# mount |grep OpenSubtitles

#

# pwd

/opt/boxee/scripts

# rm -rf OpenSubtitles/

....... snip .....
rm: cannot remove 'OpenSubtitles': Read-only file system

**Comment by Raboo** [comment]
It seems to have become persistent. It's not mounted nor can it be removed.

# mount |grep OpenSubtitles

# pwd

/opt/boxee/scripts

# rm -rf OpenSubtitles/

rm: cannot remove 'OpenSubtitles': Read-only file system

**Comment by boxeehacks** [comment]
That is the original OpenSubtitles plugin which is part of Boxee itself in that folder. You cannot remove it as it is a part of the original firmware. The only place the subtitles plugin lives is in /data/hack/boxee/OpenSubtitles and nowhere else.

Also it doesn't disable selecting integrated subtitles, it's just in a different menu. When you bring up the OSD there are a couple of buttons, one is for downloading subtitles, and another one for selecting the audio language and subtitle language. These two systems are completely unrelated, and having the Boxee+ subtitle plugin doesn't affect the builtin subtitle system for local subtitles _at all_.
