### ISSUE TITLE
TV-Show dependent ordering

### ISSUE THREAD

**Issue by FabianMeul** [boxeehacks/boxeehack#204]
Would it be possible to set the ordering mode of TV-Show episodes per TV-Show instead of system-wide?

That way, we can set the ordering on shows we are on track with to newest first, and shows we are catching up to oldest first.

Of course, the best solution would be to have a setting that would automatically jump to the latest watched episode of a TV-Show.

Your thoughts on this

**Comment by oscahie** [comment]
I'd love this... or alternatively that when a season filter is set it is remembered next time you go to that TV show. Too much clicking around to navigate to the episode you want to see, specially for shows you are still catching up with.

**Comment by FabianMeul** [comment]
Not to mention that some Episode titles could contain spoilers...

**Comment by boxeehacks** [comment]
Don't think the per-show sort order is feasible. But would love to have a jump-to-last-unwatched-episode feature!

Will look into this...

**Comment by boxeehacks** [comment]
Per-show sorting isn't possible no.

But jump to last unwatched episode will be in 1.4.0 (added on dev branch)
