### ISSUE TITLE
Can we please change the following shell script to the following (includes bash binary now)

### ISSUE THREAD

**Issue by dmike3** [boxeehacks/boxeehack#21]
# !/bin/sh

VALID_PASSWORD="secret"

export LD_LIBRARY_PATH='.:/data/hack/lib:/opt/local/lib:/usr/local/lib:/usr/lib:/lib:/lib/gstreamer-0.10:/opt/local/lib/qt'
export PATH='/data/hack/bin:/opt/local/bin:/usr/local/bin:/usr/bin:/bin:/opt/local/sbin:/usr/local/sbin:/usr/sbin:/sbin:/scripts'
export HOME='/data/hack'
export PS1='[\e]0;\u@\h: \w\a]${chroot:+($chroot)}\u@\h:\w\$'

read -s -p "Password: " PASSWORD

echo ""
if [ "$PASSWORD" == "$VALID_PASSWORD" ]; then
        echo "---------------------"
        echo " Welcome to BoxeeBox "
        echo "---------------------"

```
    cd /data/hack
    /data/hack/bin/bash
```

else
        echo "Incorrect password"
fi

**Comment by boxeehacks** [comment]
I've copied in the HOME export and a stub for the PS1; though I expect people will want to customise (I personally like to keep things a bit cleaner, and prefer the default # ), so I think we should allow people to setup a .shrc to tweak their experience. Maybe a /data/home/ that doesn't get overwritten during install of new versions of the hack.

**Comment by boxeehacks** [comment]
Hi, you can now change your password by creating/modifying the /data/etc/passwd file. This is a simple plain-text file. And you can add whatever you like to a startup profile as well which needs to be created at /data/etc/.profile . So e.g. your PS1 export can be put in the startup profile. This works exactly the same as a normal .profile in sh or .bashrc in bash
