### ISSUE TITLE
Music Visualisations

### ISSUE THREAD

**Issue by F33db3ck** [boxeehacks/boxeehack#211]
Hey Guys,

I know it's definitely a lame question... But where do you change the music visualisation ?

Projectm folder is full of .milk files

I have tried all the settings.

Kind regards...

**Comment by mnocera** [comment]
They auto-cycle during playback.  AFAIK there is no way to manually change them in the cycle.  You can remove the ones you don't like from /data/hack/projectM and reboot for a custom cycle.  You can also add more from the projectM source (http://sourceforge.net/projects/projectm/files/); the presets folder is full of milk files

**Comment by F33db3ck** [comment]
Thanx for the reply,

I wish that was the case but the only visualization i am getting is that dull native one from boxee.

Looks like he is not using the .milk files from the folder.

**Comment by boxeehacks** [comment]
Duplicate of #118

**Comment by boxeehacks** [comment]
Well ... sort of anyway :) ... just trying to keep things organised, so would be great to move the conversation there...
