### ISSUE TITLE
latest downloaded/scanned movies on the home screen 

### ISSUE THREAD

**Issue by port187** [boxeehacks/boxeehack#212]
I would love the option to see the 3 last downloaded/scanned videos on the homescreen.
Would this at all be possible?

**Comment by SendoX** [comment]
Settings/Boxee+/Home Screen   -  Home screen content - Recently added

and you see the 3 last added videos on the homescreen. (Fanart Pics)

**Comment by boxeehacks** [comment]
Yep... This is already in there :)
