### ISSUE TITLE
bugs ??

### ISSUE THREAD

**Issue by ghost** [boxeehacks/boxeehack#213]
Movies
+- [MovieName]
   +- [MovieName].nfo
   +- [MovieName].mkv
   +- folder.jpg
   +- fanart.jpg

this doesn't work for me I have it like this 
spiderman man file than
spiderman.mkv
spiderman.nfo

folder.jpg>fanart.jpg

doest work for me it shows not a fanart 
tried 720p and 1080p fanart

**Comment by boxeehacks** [comment]
Same question asked and answered in #38
