### ISSUE TITLE
startup boot_vid

### ISSUE THREAD

**Issue by emanoyhl** [boxeehacks/boxeehack#215]
hi there! thanks for this boxee+ i've been fiddling with it and have come up with something nice, however, it's not totally working which is making me wonder if this startup boot video boxee uses is on a private flash.... though, the files and config are inside the boxee itself.... and i did manage to replace both the startup boot vid and make it's configuration file editable.... 

anyway, i created bootvid.sh with:  mount -o bind /data/hack/boxee/boot_vid /opt/boxee/boot_vid
added it to the boot.sh script to call bootvid.sh
i created a folder boot_vid inside the /data/hack/boxee/ with the replacement video "video.m2ts" and the replacement cl_config file which now reads:

debug
{
   level = 0
}

pipeline
{
   mode = "FULL"
   output_filename = "NO_WRITE"
   ms_pod_test_mode = "true"
   audio_output_config
   {
      type = "I2S0_I2S1_SPDIF_HDMI"
      bit_width = 24
      ch_config = "5_1"
      sample_rate = "48k"
      out_mode = "encoded_dolby_digital"
   }
   use_video_scaling = "true"
   video_scaling_policy = "zoom_to_fit"
   video_deinterlacing_policy = "auto"
   repeat_playlist = "false"
}

inputs
{
   {
      start_with_previous_config = "false"
      input_source
      {
         filename = "/data/hack/boxee/boot_vid/video.m2ts"
      }
   }
}

i also tried filename = "/opt/boxee/boot_vid/video.m2ts"

telnetting into the boxee internal /opt/boxee/boot_vid - does in fact show my replacement video and the config file (which is writeable with nano)
same for /data/hack/boxee/boot_vid

all is there

the problem i'm having - is that well, the boxee still isn't playing the new video - it's still playing the original boxee boot up video....

i've also copied out the internal video to the sd card - to make sure it actually replaced and not renamed - and it's confirmed replaced.... just not playing new video - it's playing the old still (which is not there anymore)

can anyone help? :)

thanks!

**Comment by boxeehacks** [comment]
This is not possible. See #14, #122 and somewhat related #5

The issue is that the actual hack get's run by BoxeeHal (the Hardware Abstraction Layer that provides the interface between Boxee and the rest of the device). But BoxeeHal is only run _after_ the boot video. So there is no way to replace it.

**Comment by emanoyhl** [comment]
thanks! - i'll also keep looking into this - i just read all the references - and apologies for not digging deeper with the search (it didn't produce any startup results for some reason for me...)

thanks for the reply! i'll post again if i figure something out

**Comment by boxeehacks** [comment]
no problem; and please do if you find anything. That startup vid is driving me crazy too :)

**Comment by emanoyhl** [comment]
oh i don't mind the vid :) i just want to try the DLP trailer - haha ;) - only update i have so far is i can't do much without the decryption key lol - the iso is pretty interesting at least the /opt/boxee directory is the entire 'xbmc' section - but doesn't matter without decryption lol - anyway i have some friends to help after they finish work, etc.... 

only other thing to report is some interesting readouts in the logs of boxeehal and root-boxee.log and crypt file - but not much to do anything with.... anyway - since i'm new here - could you point me to what exactly has been done so far and any results, interesting tidbits, etc....? so i don't bombard with questions next time :)

thanks again!

**Comment by boxeehacks** [comment]
Yeah sure: definitely checkout the "Boxee root - freedom at last" thread at http://forums.boxee.tv/showthread.php?t=63248 ... that contains a lot of info on what can and cannot be done.

In addition I've tried to gather some info on the wiki: https://github.com/boxeehacks/boxeehack/wiki/_pages

When we want to do stuff with the bootup sequence we basically need to get the toolchain to build custom executables up and running. See the _Compiling Boxee_ page for some minor progress on that (though still faaaar from getting anything really working).

**Comment by emanoyhl** [comment]
wow that's a lot of reading! at least i'm more than halfway through it all.... so which specific headers are missing? i have a tar file full of linux headers for the ce4100/boxee build.... are these it? if you are able to let me know specifically what is missing from the sdk/build files for compilation that would be a big help :) sorry if this is premature - but am still going through all this stuff....

**Comment by boxeehacks** [comment]
To be honest... I have no idea :)

The kernel compilation is failing due to missing modules, but the logging doesn't show what exactly is missing even in ultra-verbose mode. Haven't yet found a way to get the right info out of it...

You could follow the steps outlined (I documented everything) and try to figure the missing components out yourself...

**Comment by boxeehacks** [comment]
Good luck ;)

**Comment by emanoyhl** [comment]
maybe they're simply trying to hide this? ^@^@^@^@#@# intel_ce_pm.ko Unofficial Build Tue Oct 11 10:19:45 EDT 2011^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@author=Intel Corporation, (C) 2009$
lol

but seriously - only compilation issues i seem to have are the locations - meaning - since canmore is already "built" with the source - the install_full.sh and run_boxee.sh scripts fail because of locations which i have to manually edit and redo - to get it to work - cross fingers.... perhaps i can attempt another build over the next few days when i have the time.... (also do you think we should start a new thread to talk about what we are working on?) 

i found they originally were using atom tools l_MID_APPDBG_p_2.2.xxx.tar.gz however, i cannot find this specific package anywhere - the latest atom tools are l_MID_DBG_p_2.3.018.tar.gz - which is available from intel's site - but don't seem to work for me...

**Comment by boxeehacks** [comment]
After installing the canmore stuff, you first need to build the toolchain. That's the thing I can't get working at the moment. That whole thing fails while building some stuff for the kernel. And some of the other modules depend on that; which in turn makes building Boxee itself fail.

There's also some issues with autoconf failing with the version that gets installed when trying to build Boxee anyway.

But have to admit; I don't know enough of make automake and autoconf to really know what I'm doing. I do a lot of software development for work, but always found it mystifying why those unix build systems are so terribly horrible. :)

I tend to solve more issues in the code itself than by having build systems generate all kinds of different outputs, so never needed anything more complex than something like Ant or Maven.

**Comment by boxeehacks** [comment]
If you do get building of the Boxee executable working though, can you update the Wiki to show how you did it, with appropriate links where possible?

As soon as I can build, there's a whole bunch of things we can re-enable... that'd be awesome...

**Comment by emanoyhl** [comment]
ok i will do that once i get everything better organized of my research thus far :)

right now though - i am working on something even better :) i kinda don't want to get hopes up - but i'll try out some of my theories on this thing - and will post results in the next few days... (sorry day job keeps getting in the way lol) :)

to appease your curiosity though check out these files:
50-udev-gen3.rules
inittab
local_tweaks.hcfg (should be empty, however, might be filled once boot, not sure on this)
memory_layout_512.hcfg
minicom.1
platform_config.hcfg

**Comment by emanoyhl** [comment]
is there a way to get in contact with you pm-wise so i don't blow up this board with comments? :)

**Comment by boxeehacks** [comment]
Yeah either contact me at the Boxee forums, or send me a mail at boxee@utalk.nl

**Comment by emanoyhl** [comment]
wow - i just sent you an email :)

**Comment by emanoyhl** [comment]
wasn't sure if you got my email.... let me know - thanks! :)

**Comment by Toliver182** [comment]
Would be interest to see what root your looking at, I've exhausted my brain trying to compile it

**Comment by emanoyhl** [comment]
what do you mean??

**Comment by emanoyhl** [comment]
so i've successfully telnetted into the boxee box without any hack - just not sure how to bring up a shell prompt other then the standard "telnet>" prompt….

another way to get into the actual console of boxee box is to telnet into it and kill the run_boxee and Boxee processes….

just not sure how to issue the kill command through telnet> prompt….

any help?

**Comment by emanoyhl** [comment]
i'm updating the wiki pages of my results:   https://github.com/boxeehacks/boxeehack/wiki/Compiling-Boxee-Part-II-(placeholder)

this is an ongoing process.... :)
