### ISSUE TITLE
Call Boxee to force rescan

### ISSUE THREAD

**Issue by thruster999** [boxeehacks/boxeehack#216]
Hi

Sorry. this should be a feature request

would it be possible to re-institute some of the original xbmc stuff

For example - send boxee a command to force a rescan of a specific share folder?

For TV shows right now the rescans appear to be random and sometimes takes hours - which is useless when you'd like to see new content asap

ie
Is it possible to force a rescan of one of your sources?
 Ie
 http://192.168.1.31:8031/xbmcCmds/xbmcHttp?command=xbmc.updatelibrary("source folder")

Thanks

**Comment by boxeehacks** [comment]
Don't worry, this is exactly the place for feature request!

This is something that's actually in the works. Working on restoring some of the old XBMC commands. Mainly to get remote updates going, and to get notifications (with things like Growl) working nicely together with Boxee.

**Comment by d4yz** [comment]
In the meantime you can go to your settings > File sources > click on the source and click rescan. The scanning seems to only work when your box is idle for over a minute and thats why it does it at random times

**Comment by mroussel** [comment]
+1. I would like to have this feature.

**Comment by boxeehacks** [comment]
There is a new service in 1.4.0 where you can do an http request to port 2100 of your boxee box followed by any of the builtin commands that Boxee has. This restores a lot of the functionality of the old XBMC http api, though with a slightly different syntax here and there.

An example to get a notification on screen:

http://192.168.xx.xx/Notification(Test,This%20is%20a%20test%20notification,2000)

**Comment by thruster999** [comment]
Great!

Paul Mercia
Cybersurf Corp.

**Comment by thruster999** [comment]
Hi

Sorry but I'm not knowledgeable enough to telnet into the box to see the commands. 

If its easy enough is there an http request I can send through port 2100 to force a rescan of one of the source directories I setup. Ie for my TV shows. So once a new one is added I can immediately force a rescan. 

Thanks

Btw great job to you and you're team. You should talk directly to dlink to get a piece of sales based on new customer purchases due to your hack. I'm one. 

Paul Mercia
Cybersurf Corp.

**Comment by boxeehacks** [comment]
You can check the Boxee DevWiki for a list of the builtin commands that are supported by the port 2100 api:

http://developer.boxee.tv/Builtins

I unfortunately don't know how all of them work exactly, because some have pretty poor documentation. But they all follow a similar approach as the Notification example I gave above...
