### ISSUE TITLE
Unreleased Carosauel Bug

### ISSUE THREAD

**Issue by d4yz** [boxeehacks/boxeehack#218]
checked put the new carosauel view and found that if you click on a movie and selected watched or unwatched and click back, the fanart on the carosauel view doesnt work. Playing a movie and going back or selecting cast and going back works fine. Seems like if the boxee loading icon pops up it quits the fanart python script and you gotta click on the popup menu and movies to get the fanart back up

Also havnt looked at your code but tv shows doesnt load any fanart in carosauel view

**Comment by boxeehacks** [comment]
Yeah... it's not done yet ;)

**Comment by d4yz** [comment]
okay figured i'd report it in to you so it doesnt get overlooked when its released and youll get the same message 20 times from different people
