### ISSUE TITLE
Browser Popups

### ISSUE THREAD

**Issue by ehrgeiz** [boxeehacks/boxeehack#222]
Hi there!

would be great if you can activate a feature that asks you for every popup "do you want to open this site".

this was in the last official boxee firmware but has been replaced with the general "allow popups" or "don't allow popups" option.

**Comment by lordoscar** [comment]
Agreed!

**Comment by boxeehacks** [comment]
After some digging, it seems like this is part of the boxee executable and cannot easily be reverted without building a new version of the Boxee executable, for which we need the full SDK first
