### ISSUE TITLE
Airplay and remote app dont work

### ISSUE THREAD

**Issue by jairofsouza** [boxeehacks/boxeehack#224]
After installing BB+, the airplay and ios remote app didnt work anymore.

**Comment by langluc** [comment]
you have updated the BB+ from setting-->BB+? 
Airplay works in my BB+

**Comment by jairofsouza** [comment]
@langluc what's your iOS version? I'm using iOS 6.0.1 and BB+ 1.3.5.

**Comment by boxeehacks** [comment]
Airplay has always been a bit funky on BB with or without the hack... I'll check this out though. Might be something related to the hostname...

**Comment by Toliver182** [comment]
Its worth noting, I have iOS 6.1 beta 4 installed on my iPhone. 5 It seems that Apple have disabled video playback via airplay on all devices that are not an apple TV. You can still output audio to it. I have tested this on vanilla boxee and boxee+

**Comment by boxeehacks** [comment]
Just tried it again, but works fine. It does show up the boxee box complete with the hack part after it in the hostname. But connects and plays just as it always did. So any issue seems to be related to the already pretty buggy airplay implementation in the boxee box.

**Comment by sarcloir** [comment]
Same problem after upgrading to iOS 6.1 (10B141). No video airplay option. Sound still works.
