### ISSUE TITLE
Music player with simultaneous web.

### ISSUE THREAD

**Issue by renatotuller** [boxeehacks/boxeehack#226]
Would it be possible to open the browser, the music player does not close?

**Comment by boxeehacks** [comment]
Probably not. The web-browser is (as far as Boxee software is concerned) a media player (could be youtube or something similar) so it will close any other current media player, whether it's video or music or whatever...

I'll check to see if something is possible. But probably not...

**Comment by boxeehacks** [comment]
Nope... cannot be done unfortunately without a new boxee executable. However that's still not possible until we have access to the SDK
