### ISSUE TITLE
Request: Scheduled times for re-scans

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#228]
One request with Boxee I had was for the daily re-scan of sources to have a timing function, so that it always occured in the middle of the night when it would disturb no one (due to slowing the boxee down). Plus the current issue of daily scan is that the timer is reset to 24hours after every manual scan, or if the boxee is powered off and then on again the timer starts at whatever time you power back on. As such you can never be sure at what time the next scan would occur.

With Boxee+ would it be possible to add an absolute time for the daily rescans to occur?

**Comment by boxeehacks** [comment]
Would probably be possible. Will look into this. I personally just set it to hourly scans to make sure new content gets picked up in a timely fashion...

**Comment by boxeehacks** [comment]
This can be achieved with mape's cron system in combination with the new http api. Will add some wiki content for something like this later. Will probably be a plugin of some kind, since most people will be served just fine by using the hourly scan...
