### ISSUE TITLE
[QUESTIONS] - Trailers

### ISSUE THREAD

**Issue by JGKos** [boxeehacks/boxeehack#229]
ok...

I ave decided to add the trailers to my EMM settings, and have updated my library with them.  When I resync my db with boxee+, I do see the trailers there, but half of them are showing up as unidentified.  Is there a setting I am missing, or file name check I need to do to get these to sync correctly?  I really do not want to have to manually identify all these via the boxee remote

much thx

**Comment by boxeehacks** [comment]
There is a setting in the regular Boxee settings which tells Boxee to not identify files below a certain file size. This is intended for things like trailers.

In addition the NFOs can contain trailers. There is a plan for adding functionality (in the future) to show these in the trailers section for a movie, but that is future thinking... no specific timing planned yet.

See issue #64 for tracking this feature...
