### ISSUE TITLE
Automatic fanart downloading

### ISSUE THREAD

**Issue by hessius** [boxeehacks/boxeehack#23]
The added fanart function is awesome. What would be even more awesome is if the boxee box could download the fanart files automatically.
Several reasons for this, among others:
You might run an application on your computer to download fanart for your entire library once, but what happens when you add new shows and movies? You're probably not going to rescan and redownload every time?

Also the applications I've tried all try to identify my media, not only wasting time by performing a job already done by the boxee box but sometimes failing or misidentifying (sure, the box isn't perfect in this area but at least the fanart will match the media identity on the box)

**Comment by felipesalomao** [comment]
Agree, would be nice add, for example i download nfo files to boxee for movies and music videos.. Would be great if fanart would be get image from this nfo file for example.. Actually its take much time to find fanart..

**Comment by boxeehacks** [comment]
The best approach really is to have a media manager provide all the NFOs and fanart so the Boxee Box doesn't have to scan again. If you name everything properly the Boxee Box will never scan using its scraper.

That said, I think it might be possible to try and find out whether there's a fanart image or not, and try and query themoviedb for an alternative if not. Bit tricky though, but can look into it...

**Comment by felipesalomao** [comment]
Somebody is developing it ?

**Comment by dmike3** [comment]
I don't think so. I think we might be better off using an application the same way we pull NFO information. I was just checking under XBMC's version of the fanart downloader and people are complaining about the quality of the images, and the suggestion was to use a third party program. So I don't think even with XBMC that they are doing it really well either.

Anyhow, I'm sure somebody with some good python knowledge could figure out the artwork.downloader done by XBMC. It's up on GITHUB.

**Comment by boxeehacks** [comment]
Agree with mike3y, if XBMC can't even git it right, let's not try and complicate this already huge project.

Much better to have a separate scraper anyway like Ember Media Manager or ViMediaManager. For now not going to do anything about this. However when we deal with the scrapers in general in the future will pick this up again...

**Comment by hessius** [comment]
I've been giving this some thought. Been trying with EMM and ViMM but I still can't manage to collect fanart for more than approximately 50 % of my movies. As of 1.4 fanart is more emphasized and movies lacking fan art seem incomplete.

So I've been checking out TMDB - http://tmdb.org - which seems to have quite HQ (at least 720p) backdrops of all random movies I tried (from hollywood blockbusters to a black and white british film and a norwegian movie (and its sequel I didn't know about))

What also struck me was the (seemingly) very easy API - http://docs.themoviedb.apiary.io

Would it be possible to add a JSONP call to tmdb if no fanart.jpg is found? If found on tmdb the image could either be added to the movie folder (probably hard) or added to the cache and/or and external drive. If nothing is found on TMDB it could just display the background.

Should be possible by first searching by name to get the id of the movie: http://docs.themoviedb.apiary.io/#get-%2F3%2Fsearch%2Fmovie
And then grabbing images: http://docs.themoviedb.apiary.io/#get-%2F3%2Fmovie%2F%7Bid%7D%2Fimages
FIlters for vote or dimensions could probably be added

**Comment by robnz09** [comment]
I love this idea. It would be awesome to have an automated scrape of fanart from a source such as tmdb. If this issue has been closed by boxeehacks do we need to reopen it? Would be great for them to see if they could make your solution work.

**Comment by tobbewilson** [comment]
+1

**Comment by rafasnunes** [comment]
Ember Media Manager is very handy! But I don't know why my Boxee is not identifying the fanarts for the TV Shows. Just for the Movies... any trick?
