### ISSUE TITLE
File transfer issue

### ISSUE THREAD

**Issue by Baek87** [boxeehacks/boxeehack#231]
I've noticed that Playback is unwatchable and a/v is totally out of sync when transfering files to HDD attached to boxee box.
Its over the SMB protocol. Maybe it is what it is but maybe it can be fixed?

Thank you for your time and work on this awesome project! :-)

**Comment by boxeehacks** [comment]
Could you explain a bit more? Are you watching the videos on your boxee box or on your computer. How are you transfering the files? Does the same happen if you play them from your computer without placing them on the boxee box attached hdd? Is it specific files, or all files that you play in this way? Filesize vs. duration... maybe the bitrate is too large?

Any additional info would be very helpful in pinning this down...

**Comment by boxeehacks** [comment]
Please provide additional info. Will reopen this issue if we can pin down what the cause is.

**Comment by Baek87** [comment]
hey again!

my problem is when i see a movie on the boxeebox using usb attached harddrive number 1, and i then go on my windows pc and then transfer another new movie (large file) to harddrive number 1 over network (SMB, windows file sharing), then the playback studders! its only when i transfer to the same harddrive as the movie is played from. it dosn't matter what quality the playing movie is in. 

Thanks. ;)
