### ISSUE TITLE
Can't access to my external hard disk connected to BOXEE

### ISSUE THREAD

**Issue by langluc** [boxeehacks/boxeehack#235]
I have a problem: it's that i can't access to my hard disk (BOXEE) connected to BoxeeBox from my Pc. The error is Can not find username
The BB+ version is 1.3.5 and I have windows 8. Before i upgraded to BB+ i can see the HD.

![3c22967a-4b7a-11e2-890f-13269b538d13](https://f.cloud.github.com/assets/3002712/28648/e9b139b2-4c6b-11e2-9b10-e8365cc07e1c.png)C

**Comment by ghost** [comment]
its a windows 8 problem I had it to instald windows 7 now 4 hhd works perfect for me

**Comment by ffiliere** [comment]
I am using windows 7 and am having the same issue. Mine used to come up as boxee and now shows up as intelce and when i click on my boxee hard drive  i have the same issue. I am a total tard when it comes to dealing with networks will some one point me in the right direction to get this issue resolved

![boxee](https://f.cloud.github.com/assets/3106056/45446/7c795fee-5785-11e2-8247-31f145bc242d.jpg)

**Comment by ghost** [comment]
it works for me on windows 7 why did you changed the network name of boxee leave every thing deafault I wil show you wait

**Comment by ghost** [comment]
![Untitled](https://f.cloud.github.com/assets/3061517/45466/d4ee9ad0-5786-11e2-9dcd-9741d444f6cb.jpg)

**Comment by ghost** [comment]
![Untitled](https://f.cloud.github.com/assets/3061517/45468/f1fb913c-5786-11e2-8d63-3888f3ea0d94.jpg)

**Comment by ghost** [comment]
can you map the network drive right clic than map network drive than choose a letter than when you go to my pc you see the drive there its much easyer to acces

**Comment by ghost** [comment]
![Untitled](https://f.cloud.github.com/assets/3061517/45473/4380b258-5787-11e2-9925-eec8263bd457.jpg)

**Comment by ghost** [comment]
are you the administrator update windows drivers etc

**Comment by langluc** [comment]
Go to setting in boxee and write "workgroup"in windows sharing. 

Il giorno 05/gen/2013, alle ore 23:16, ffiliere notifications@github.com ha scritto:
