### ISSUE TITLE
Increase the size of the plot field in the film overview screen.

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#236]
My Library film is fully optimized with EMM. I noticed, however, that the plot is not always entirely displayed in the overview screen of each film. The problem could probably be solved by increasing the size of the space assigned to the plot in each film's overview screen.

Can anything be done?

**Comment by tennisbgc** [comment]
Im using MC and the overview is used on the overview page and the plot is used on the index page in list view.

**Comment by saragusa** [comment]
EMM also allows to distinguish between plot overwiew and plot index page in list view. But anyway, even in the list view, in the plot of the index page, many times the space is not sufficient, and the text is interrupted .....

**Comment by boxeehacks** [comment]
Size increased in 1.4.0

**Comment by saragusa** [comment]
I'm sorry. Unfortunately it is not enough .....

**Comment by boxeehacks** [comment]
But we cannot increase it further or it will cause issues with the trailer support and other parts of the UI. Maybe in the future we'll add something for scrolling the text, but the area will not increase anymore.

**Comment by saragusa** [comment]
Thanks very much... You are a serious Hack....(;.....)

Inviato da iPhone

Il giorno 11/gen/2013, alle ore 11:15, boxeehacks notifications@github.com ha scritto:
