### ISSUE TITLE
No Indication of Keyboard Status / Mobile-style Password Fields

### ISSUE THREAD

**Issue by walesmd** [boxeehacks/boxeehack#237]
Currently there is no indicator of keyboard status, particularly capital letters (alt you have to hold, that's fine I think). This can make it extremely difficult to enter passwords correctly as the user is unsure as to whether they are entering a lower or capital letter within password fields (this may be limited to the Boxee Browser, I believe the Boxee interfaces all have "Show Password" options).

I have not looked into the availability of monitoring remote input outside of the bootloader protected areas of the system so I can't say with any amount of confidence the feasibility of these proposed solutions.
1. Near-term solution: Hook into the remote input, when CAPS is pressed use `dtool` to change the hardware LEDs to orange (like debug), when CAPS is off the logo returns to its normal green color.
2. Relatively simple solution but it feels dirty/sloppy: Implement custom functionality into the Boxee Browser. During DOM traversal, if `input type='password'` elements are discovered inject a new `checkbox` element w/ JavaScript listeners that would cycle the `password` input between `text` and `password` giving the user the ability to see their password in plain text.
3. Optimal solution: Modify the `edit` of Boxee's GUI API to implement a hybrid solution popularized by mobile platform like Apple's iPhone and Google's Android. The last character of the user's string is visible in plain-text, only being masked by the asterisk once the user has entered a following character or after a short, predetermined timespan (3-5 seconds). This provides the user ample opportunity to visually confirm the characters are correct as they are typing while maintaining the security of obfuscating the password to prevent "over the shoulder" reveals to third parties.

**Comment by gadgetchnnel** [comment]
I'm not sure if it is possible to detect the CAPS button, as I think this is actually handled by the remote itself. I believe it simply sends different key codes for the other buttons depending on whether CAPS has been pressed - which is why you can get strange results from pressing Alt when CAPS is enabled (due to CAPS shifting the key codes by a fixed amount).

**Comment by boxeehacks** [comment]
Yes, as far as I can tell the remote just sends the appropriate character either uppercase or lowercase and there is no way to handle this in the UI. Just tapping enter on such a password field brings up the Boxee edit screen though where it will always show the latest character, so you should be able to see what you entered just fine...

Nothing we can do about this one, but not that necessary either if you use the Boxee edit dialog for it.
