### ISSUE TITLE
Enable Karaoke mp3+cdg files (ala XBMC)

### ISSUE THREAD

**Issue by BillDorrian** [boxeehacks/boxeehack#238]
Will Karaoke files (mp3+cdg) be supported in the near future, like XBMC?

**Comment by boxeehacks** [comment]
Not unless we can get a way to compile our own version of the Boxee executable. This is still not possible because we don't have access to the required Intel SDK. This functionality itself is stripped out of the Boxee executable and cannot be added back in without that SDK.
