### ISSUE TITLE
Manual or better search for subtitles

### ISSUE THREAD

**Issue by feelgoodvince** [boxeehacks/boxeehack#242]
Sometimes looking after a subtitles doesn't work as intended.

Boxee recognises the movie as the correct movie, let's say "the cold light of day" but the filename is: 
RELEASE-tclod-xvid-ac3.avi. I think boxee uses the filename in stead of the movie name... so i don't get the correct results. 

So i think it would be great if you could choose to manually search for a subtitle or advanced search or something like that...

**Comment by boxeehacks** [comment]
The new version (coming out in a few days) has file-hash based checking which should improve for those situations where the filenames are wrong. Much better results will always be had though by just renaming your files properly; using something like Ember Media Manager to do so should cost you almost no time per movie, and will also give you proper NFOs with media information, correct posters for all movies and fanart...

**Comment by Grill-B** [comment]
Just wanted to recommend mediacentermaster.com for fixing foldernames and file names fanart, subtitles and stuff automatically and alot of other nice things to! Works great with boxee.
