### ISSUE TITLE
Cant log in on my USB disc when update BOXEE+

### ISSUE THREAD

**Issue by bakerman1972** [boxeehacks/boxeehack#244]
I updated and now i cant wiew or see my usb disc ?
I got no access 
anyway to fix this so my other boxee can wiew my files/movies on USB disc

**Comment by boxeehacks** [comment]
how are you trying to access the disk?

via windows file sharing ? If so you may need to use the ip-adress instead of the name of the boxeebox. So e.g. instead of \boxeebox\whatever use \192.168.2.8\whatever

**Comment by bakerman1972** [comment]
will try that nice thanks

**Comment by bakerman1972** [comment]
via windows file share
