### ISSUE TITLE
Request: Rescan folder "date created" order instead of scanned order..

### ISSUE THREAD

**Issue by Grill-B** [boxeehacks/boxeehack#245]
Hi
I have a request that when boxee rescans. Movies should be added by "date created" order instead of scanned order for the "Recently added" movies to work.

Now its just a mess when rescanning.

**Comment by boxeehacks** [comment]
I know... and sometimes old stuff keeps getting readded to the top. Pretty terrible.

There's already an issue for this though.

Duplicate of #19
