### ISSUE TITLE
Update 1.4.0

### ISSUE THREAD

**Issue by louout** [boxeehacks/boxeehack#246]
Hi

First of all well done on a awesome project but I was Hopeing you could help. 

I am unable to update Boxee to 1.4.0 after original hack. My Boxee is still showing I am on 1.3.5. I have tried to run  "check for new version" this says I am up to date. 

I have also tried redownloaded the install package and updating the install contents on my USB stick with no joy. Please help.

**Comment by PiteH** [comment]
1.4 is still in development, So your updater is just fine. You just have to wait until it is released.

**Comment by louout** [comment]
Thanks for that, Sorry misunderstood what the milestone were for.

**Comment by boxeehacks** [comment]
Yeah the major tasks have been done, but still finishing up on some last bugs 'n' stuff. It will be out this year though!
