### ISSUE TITLE
Feature request --> iTunes support

### ISSUE THREAD

**Issue by basdp** [boxeehacks/boxeehack#248]
Today I installed Boxee+ for the first time after my son (who owns a Boxee too) told me that Boxee will stop with all future enhancements and updates.

All functions seems to be working and I'm happy to know that my Boxee is not dead.

Now that the music option is new with Boxee plus, I would love to have an integration with iTunes or even better iCloud (music)

Do you think this is possible? Is it allready on your wish list maybe :-)

Thanks,
Rien

**Comment by diff3** [comment]
Not sure if we can do this without recompiling boxee. But we can probebly use third part programs to stream music from itunes library.

**Comment by boxeehacks** [comment]
Maybe if someone hacks the protocol for iTunes/iCloud music it might be possible, but that seems like a long long way away. What I currently do myself is have one computer in the house with iTunes which downloads all the iCloud music. Share the iTunes Music folder using Windows File Sharing, and add that share to the Boxee Box. Then you can browse all that music via the music section. At the moment that's the only way...

**Comment by basdp** [comment]
Thanks.
I am downloading all music from the iCloud to a Mac Mini server now and will share this with the Boxee. As far as I found out, downloading music from iCloud with iTunes is a manual action. Any idea if this can be automated?

THanks in advance
