### ISSUE TITLE
Feature request --> Custom shows support

### ISSUE THREAD

**Issue by basdp** [boxeehacks/boxeehack#249]
One of the cool features is the shows are automatically detected. But as far as I experienced, this only works for predefined shows.
As I live in the Netherlands, I like to add our local shows to the boxee. Is it possible to add custom shows ?

Thanks,
Rien

**Comment by boxeehacks** [comment]
Yes you can use NFO files to tell Boxee what a show is; this will prevent it from searching (and not finding) it itself. See the Boxee support pages for info, or check the forums.

E.g.: http://support.boxee.tv/entries/510215-creating-an-nfo-file

**Comment by basdp** [comment]
Thanks... I didn't knew that.....
