### ISSUE TITLE
Fanart not working

### ISSUE THREAD

**Issue by Jamflava** [boxeehacks/boxeehack#261]
Fanart is not working in version 1.4.
Tried to clear tumbril cache, did not work.
Only seems to work in the new "viewing mode".

**Comment by d4yz** [comment]
We need a little more information. The fanart really will work mostly in the new view mode. Where else are you expecting to see it? Are all your movies in their own folder with a fanart.jpg in the folder. Same for tv shows. Make sure that the fanart is actully "fanart.jpg" not fanart.jpg.jpg and recommended to keep fanart in lower case letters.

**Comment by jesseblue** [comment]
did you try to restart as well? fanart works on my bbox

**Comment by Jamflava** [comment]
In the new mod they are working (and on the home screen), but when i try one of the other view modes and i select a movie, i dont see them.

I already did a few restarts.

**Comment by d4yz** [comment]
Where dont you see them? when you actually click a movie and see its overview or when you see the movie title and are trying to select a movie?

**Comment by boxeehacks** [comment]
None of the other view modes will ever show fan art. That's only in the new dedicated fanart view (the carrousel), on the movie details page, on a TV Show details page or on the new fan art home screen.

But if you're in one of the other view modes and you select a movie, it should work though; so I'll look into why that may not happen...

**Comment by boxeehacks** [comment]
Ah... and found it. With all the festivities tomorrow it'll take while before it's updated but I'll push out a quick update soon to address this.
