### ISSUE TITLE
Shows Button Not Showing on Home Screen or Submenu

### ISSUE THREAD

**Issue by drunkwithpower** [boxeehacks/boxeehack#266]
Just upgraded to Boxee + v1.4 and now I don't have a Shows button on my Home Screen or my submenu. I have no way to enter the Shows section to watch TV shows.  When I access the Boxee + settings I see the Shows option (under Home Screen) but it is not a toggle to turn on/off, but reads built-in.  I don't know how to change this to show the button again.

Thanks!

**Comment by ghost** [comment]
reboot fixes this

**Comment by JGKos** [comment]
yup, just rebooted, mine is back as well

**Comment by drunkwithpower** [comment]
Cool.  I just rebooted and it fixed it as well.  Sorry about the false alarm.

**Comment by colby-makowsky** [comment]
Why are we closing this? If everyone has the same issue...?

**Comment by jesseblue** [comment]
because a reboot fixes the issue
