### ISSUE TITLE
Issues with 1.4.1

### ISSUE THREAD

**Issue by scoobshub** [boxeehacks/boxeehack#267]
- fanart in home started appearing only after the activaction of the new view mode
- fanart in the tv show episode list started appearing only after using the new view mode (have to do this every time a new show is scanned and added)
- fanart in movies are not appearing at all in any way
- strage things happen if I want different view modes in movies and tv show (eg both changing at the same time)
- randomly, after i disconnect the account and login again, my icons disappear (except for file) and i have to reload the skin

**Comment by bengarsle** [comment]
i have trouble with fanart...boxeehack_grab_fanart.py comes up in the right corner

**Comment by VictorV0nDoom** [comment]
the boxeehack_grab_fanart.py script will occasionally fail and stick with last image shown unless you change directory's and go back thus restarting it.

**Comment by bengarsle** [comment]
were do i change directorys do you mean in the computer?
i am no good at this so please if you can help me tru..

**Comment by VictorV0nDoom** [comment]
no when you go to ex: apps or setting then go back to home screen the script resets. do you have fan art set up in your movie folders?

**Comment by bengarsle** [comment]
yes the fanart is set up in movie folders

**Comment by VictorV0nDoom** [comment]
some of the image settings dont seem to take till you change the view modes and back or reboot.

**Comment by bengarsle** [comment]
i will try and see if it work..thanx for the help..

**Comment by boxeehacks** [comment]
Also if you have such an error, please get the boxee logs and send them to us. This will help tremendously!

**Comment by boxeehacks** [comment]
These issues have now been fixed (keep an eye out for the next release version). In the future also please make separate entries on github for multiple issues that you're having, so each one can be closed or opened separately.
