### ISSUE TITLE
Fanart.jpg

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#271]
why it shows me not at all fanart.jpg? Some work, some do not work.

**Comment by boxeehacks** [comment]
Can you give me a folder structure for a fanart that doesn't work?

**Comment by d4yz** [comment]
Make sure fanart.jpg is all lowercase

**Comment by SendoX** [comment]
is all in lower case !

my folder structure :
-Movie Folder
--Movie.avi
--fanart.jpg
--movie.nfo
--movie.tbn

**Comment by gadgetchnnel** [comment]
I've had the same problem with TV shows. I then found that if I switched to the new fanart view mode and then back to the thumbnails view mode, all the fanart appeared as it should. It looks like fanart is only being grabbed when in the fanart view mode, but once grabbed this is retained across view modes.
Unfortunately, this doesn't seem to stick permanently. Every time I go into Shows, I need to go to fanart mode and back to thumbnails to get the fanart.

**Comment by ghost** [comment]
I have the same "problem"...
.....then found that if I switched to the new fanart view mode and then back to the thumbnails view mode, all the fanart appeared as it should. It looks like fanart is only being grabbed when in the fanart view mode, but once grabbed this is retained across view modes.
Unfortunately, this doesn't seem to stick permanently. Every time I go into Shows, I need to go to fanart mode and back to thumbnails to get the fanart.

**Comment by d4yz** [comment]
It looks like there is a fix for it, just needs to be pulled into the main branch and everyone should get it soon

**Comment by ghost** [comment]
Sounds good, looking forward...

...It looks like there is a fix for it, just needs to be pulled into the main branch and everyone should get it soon

:o)

**Comment by boxeehacks** [comment]
Should be fixed now in new version (will update today)
