### ISSUE TITLE
Pandora added to music icon choices. 

### ISSUE THREAD

**Issue by ndillon** [boxeehacks/boxeehack#274]
Please add Pandora as a selection for the home screen under the music selection along side Spotify and Grooveshark.

**Comment by boxeehacks** [comment]
Is there already a pandora app on Boxee? If so this shouldn't be a problem to add...

**Comment by ndillon** [comment]
Yes, there is a Pandora app in the official boxee apps section.

**Comment by khals** [comment]
I'd love to see this working aswell :)

**Comment by ShadowSloth** [comment]
+1 to this request!

**Comment by Jchromeo** [comment]
Me too. I don't know anyone that uses grooveshark.

**Comment by boxeehacks** [comment]
Done! Will be in the next release
