### ISSUE TITLE
Bug: ABC shortcut on the side does not work

### ISSUE THREAD

**Issue by jesseblue** [boxeehacks/boxeehack#275]
am in the regular view and trying to get tot the movies starting with 'S' and it does not go to those movies. it stays where you currently are...

**Comment by boxeehacks** [comment]
Which view are you in? There are 4 at the moment:
- List
- Icons
- Small icons
- Carrousel

**Comment by jesseblue** [comment]
i only looked at the icons view..

the carousel view does not have the ABC list...

i will check later for the list and small icons...

**Comment by jesseblue** [comment]
hmm...it did work for the small icons and list view and now it also works for the regular icons menu...

consider this closed.
