### ISSUE TITLE
Identifying episodes automatically

### ISSUE THREAD

**Issue by tbone7467** [boxeehacks/boxeehack#278]
When Boxee tried to Identify my episodes manually it get stuck on dumb stuff ,for example:

The A-Team I have named A-Team, The.

It also doesn't understand S1E01 Seems it is looking for S01E01 format is there anyway to have it rescan unidentified content with a secondary search criteria?

**Comment by boxeehacks** [comment]
Best way to solve this is to have proper NFOs for all your files.

Otherwise only way to solve is by having a different/better scraper.

See #209 #9
