### ISSUE TITLE
Flash update

### ISSUE THREAD

**Issue by tekkietekkie** [boxeehacks/boxeehack#279]
Any chance of a flash upgrade? The version is old and using the web browser for some sites like itv player doesnt work anymore:(

**Comment by sphinxlady** [comment]
They don't have acess to the core of boxee software so the flash update wont happen through this.

**Comment by tekkietekkie** [comment]
Ahh that sucks :(

**Comment by D34dmeat** [comment]
Im not a linux wiz but since 1.4 the ftp access takes you to the root of the running system so shouldent it be possible to exchange the libflashappdata.so that resides in lib/ or atleast implement a shellscript that exchanges this and mabey a few others at startup

**Comment by boxeehacks** [comment]
Duplicate of #46 #12
