### ISSUE TITLE
script error with boxeehack_grab_fanart.py

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#281]
hi...
i have a script error with boxeehack_grab_fanart.py.
![740017_484906458217838_745732076_o](https://f.cloud.github.com/assets/3018141/36410/f9406752-532a-11e2-8552-2a0516a4994f.jpg)

**Comment by T-bird-se** [comment]
Same here
Maybe related to language setup as the only ones I seen complaining about it over at boxee forums had an non English setup, and I run it in Swedish

**Comment by oscahie** [comment]
I have it in English and have also seen that error message.

**Comment by boxeehacks** [comment]
Can you download your boxee log files (directly after this error happens) and send me the root-boxee.log file?

**Comment by T-bird-se** [comment]
You can see some in this post http://forums.boxee.tv/showthread.php?t=64648&p=289933#post289933

**Comment by T-bird-se** [comment]
Hi
Sorry for late answer but this mail isn't monitored on a daily base

I set the log level to "error" and attached is the result

Thx for the hard work on boxee+

/T-bird  

---

 Från: boxeehacks notifications@github.com
Till: boxeehacks/boxeehack boxeehack@noreply.github.com 
Kopia: T-bird-se tbird_se@yahoo.se 
Skickat: måndag, 7 januari 2013 1:24
Ämne: Re: [boxeehack] script error with boxeehack_grab_fanart.py (#281)

Can you download your boxee log files (directly after this error happens) and send me the root-boxee.log file?

**Comment by KarlSponholz** [comment]
I had the same problem. The problem are special characters like "ä,ü,ö,ß". I replaced them with "ae, ue, oe and ss" in the title-tags in the movie.nfo files and get no more error.

**Comment by boxeehacks** [comment]
Hi guys,

I've finally been able to pin down this bug. Thanks a lot of for the input, couldn't have done it without it. I'm wrapping up some dev on this now and will put out a new version somewhere today which should finally fix this!
