### ISSUE TITLE
Crashing after leaving YouTube app

### ISSUE THREAD

**Issue by fradchad** [boxeehacks/boxeehack#286]
The whole system freezes after leaving the YouTube app. This just started with 1.4. On the prior version this piece worked correctly.

**Comment by boxeehacks** [comment]
Have you been able to reproduce this more than once? I cannot get this same behaviour. Also please check if you start up the boxee box and use youtube immediately vs. after using airplay (if you have airplay enabled).

**Comment by boxeehacks** [comment]
Closing since no feedback given...
