### ISSUE TITLE
Shutdown not working properly

### ISSUE THREAD

**Issue by fradchad** [boxeehacks/boxeehack#287]
I know this was a core bug with Boxee firmware. The shutdown process 70% of the time results in the yellow icon and you have to force Boxee to turn off by holding the button down. 

If this can be fixed that would be AMAZING! Been waiting for a year to get this issue fixed.

**Comment by xler8r** [comment]
Heyo, I'm having a similar issue. In my case however there's two issues...
-Issue 1: By clicking on "Shutdown", it actually does nothing.
In this case I have to press the hardware button to turn it off.
-Issue 2: By clicking on "Shutdown", it reloads the homescreen...or something like that. It doesn't actually reboot the entire system, it just instead makes the screen go blank and then it returns to the homescreen.

Edit: After 4 times of retrying issue 2, it successfully shut down. The next time I turned on Boxee and shut it off... Shut Down worked properly the first time I tried it... so it looks like this can be inconsistent.

**Comment by seamusallen0905** [comment]
I have had exactly the same issue, xler8r, but it got to the stage that I could just start browsing through my movies and it would go back to the home screen reloading sequence.  
I eventually had enough and disabled boxee+hacks by switching off smb sharing (where its enabled). 
Rebooted and there was an error at some stage on the re-booting that said something about script *****.py fault. It seemed fine for a while, but then after a few minutes, its started rebooting (not from scratch) but from the Boxee menu screen.  I gave up and re-installed the stock firmware from the recovery menu. Rebooted and the box was doing the same thing!!  Deleted all the info in the databases, caches, cookies and everthing else possible under the advanced settings in the system menus and this solved the problem with the rebooting. Therefore the only explanation is that the sqlite database some got corrupt somehow. Hope this helps someone else. Will re-install Boxee+Hacks again soon, not sure that this was the cause.

**Comment by boxeehacks** [comment]
There are also some other issues which are new and specific to 1.4.1.

See #262 (and it's duplicates #287 and #308)
