### ISSUE TITLE
TV Show not showing on Home Screen afte 1.4.1

### ISSUE THREAD

**Issue by UffeTei** [boxeehacks/boxeehack#291]
After updating to version1.4.1. I cannot not see the TV Show icon on the Home Screen anymore, but can still access them via the Files icon.

All the shows I have have individual nfo's

**Comment by gadgetchnnel** [comment]
I had this after first updating (I was missing most of the icons). Another reboot fixed it. I assumed that the update made some changes to the boot script which required another reboot to take effect.

**Comment by vipera66** [comment]
The same thing happened to me. Rebooting also fixed it.

**Comment by UffeTei** [comment]
Issue solved with rebooting the system.
