### ISSUE TITLE
Unlock Geo location Applications

### ISSUE THREAD

**Issue by BeRadNz** [boxeehacks/boxeehack#292]
This used to be a feature in a release some time back, if someone could get the code from a past firmware and put this back that would be amazing! 

I think from memory there was a check box in the settings menu to display applications such as the BBC iPlayer application if you where not in the UK, With a good dyno DNS we can get these apps running for all :)

**Comment by boxeehacks** [comment]
Unfortunately this is not possible. This requires modifying the Boxee executable which is not possible due to a missing Intel SDK.

Also I'm not in the UK (or US) but I do see the iPlayer and Netflix apps without any problems. They just won't work, but they're still there...
