### ISSUE TITLE
Carrousel  change timer

### ISSUE THREAD

**Issue by sphinxlady** [boxeehacks/boxeehack#293]
Not so much a bug as a feature request.
It changes fanart quite quickly and a option to set different set times for it to  do this would be good.

20's  30's' 60's  or the like since it doesn't give a person much chance to enjoy the art as it is.

**Comment by DarkAllMan** [comment]
I would like to see this also!
I also noticed that not all of my shows have fanart, which results in the fanart carrousel having some no background screens...... please make the carrousel ignore shows without fanart!

**Comment by boxeehacks** [comment]
There is a bug fix coming out soon that gets rid of the blank screens (when there's no fanart)

Will add the timer. The default is going up slightly in the next bugfix release. Not sure when manual controls are coming though (if at all)...

**Comment by boxeehacks** [comment]
Timer now is a bit longer. Not adding manual controls yet though, because the settings menu is already becoming quite cluttered and I want to keep things simple. In the future this will possibly be editable using advancedsettings.xml or something.
