### ISSUE TITLE
[Question] - fanart

### ISSUE THREAD

**Issue by JGKos** [boxeehacks/boxeehack#294]
Any chance fanart will ever work with backdrop.jpg?

Carrousel View thumbnails, any way on increasing their size?

much thx

JK

**Comment by boxeehacks** [comment]
No it will always be fanart.jpg. This is (as far as I can tell) the standard everywhere, so just do a rename across your drives and it'll all work fine.

The carrousel view thumbnails are now the standard sizes also used elsewhere. This makes things consistent. Also increasing the size would obscure a lot of the fanart, which was the main point for this new view, if too much is obscured then there is no reason to use this view anymore. So probably not going to happen no...
