### ISSUE TITLE
Request- fan art + recently added 

### ISSUE THREAD

**Issue by tekkietekkie** [boxeehacks/boxeehack#295]
I love both of these options but having a small recently added overlaying the fanart would be awesome, i use my boxee for tv and right now i am constantly looking on sabnzb with my ipad to see what is recent. So if possible to create an option that does both.

Or maybe another option is by the icons have one for history? Maybe an icon at the right side beside web and when you select it you can see the new things since the last scan... Not sure if thats possible or not.

Or better yet how to setup growl :) if sab could send the alert that would be awesome.

**Comment by boxeehacks** [comment]
you can use the HTTP API to have Sab send the notification. Just use:

http://theboxeeboxip:2100/Notification(Title,Message,2000)

Load that into your browser (change theboxeeboxip with the actual boxee box IP address of course) and you should see a notification on your TV. You can use this to trigger any of the builtin Boxee commands (see the Boxee DevWiki for more info)
