### ISSUE TITLE
Request: iPlayer option on home screen not at Shows expense

### ISSUE THREAD

**Issue by LewisFamily01** [boxeehacks/boxeehack#296]
I love the new option to put the iPlayer APP on the home screen as a main menu option.

However I also have local TV show content, and now it means that I have to choose between having the iPlayer option or the TV Show option.

In reality I want both. 

In my case, I have turned of some of the other options, e.g. watch later, friends etc so have room on the menu for more options.

It would be really really good if there were 8 user definable menu entries, and then each menu entry would have the same selection of options in the settings menu. Thus you could choose the position in the menu for TV Shows, (you may want it on the left, you may want it on the right etc), you could choose to have iPlayer and TV Shows etc. You could also choose which of the menu options should be the default selected Icon when returning to the home screen (depending upon what you use most often)

Keep up the good work, I thought 1.3.x was great, but 1.4.x and fanart support has really pimped this ride... :-)

**Comment by d4yz** [comment]
I believe there will be an update in the future where you will be able to keep your local buttons and have the apps as well. I agree it doesnt make much sense now but its only to see if it works and what not. I know solitude doesnt want the main interface to be much different then boxee and wants to keep that boxee feel

**Comment by D34dmeat** [comment]
The problem is that when you add icons to the home menu, for some reason they do not scroll, so i made a dropdown menu for it. Sad to say i have to fix my git repository so i can submit the changes.

**Comment by boxeehacks** [comment]
Yeah there will in the future be a way to add custom icons. This was just the first step :)

This is a duplicate though of #263
