### ISSUE TITLE
Request - movie plot in fanart mode and language select!

### ISSUE THREAD

**Issue by roberardo** [boxeehacks/boxeehack#299]
Hi,

Congratulations for the excelente work, i am loving Boxee Plus!

I use Boxee Box only for my personal movies via USB (Two HDs)

I have two requests if is possible:

1) i loved the fanart view mode, but you could put the plot in the middle of the screen like XBMC?

2) i exported from XBMC all fanarts, folders and nfo files for my 300 movies, but i think Boxee is too slow accessing this data... when it gets from the internet the access is quickly, but i like my nfo in portuguese Brasil. XBMC get the data from MovieDB in portuguese, doing this for boxee is very dificult? it is possible?

Thx

**Comment by lune001** [comment]
I'd love to see language selection for data online !

**Comment by boxeehacks** [comment]
In the future, if you have two requests, please make two separate issues. That way both can be handled better independently.

As for issue 1. This will probably not be added. The whole point of that view is to view the art larger, and obscuring that with more text kind of negates that idea. In the future I may add an optional screen with that info though, but it's low on the priority list.

As for issue 2. If you want to have specific text in the movie info, then using NFOs is the way to go. The Boxee scraper itself is very limited and cannot be made to do what you want.

See #9 and #209; in the future we will probably add a method to add custom scrapers. Then you will probably be able to use MovieDB with specific language as well.
