### ISSUE TITLE
Display Fanart for "Flattened" TV Show Folders (Plus on All Seasons & Individual Seasons)

### ISSUE THREAD

**Issue by KevinSartori** [boxeehacks/boxeehack#30]
Like my Movies, I have all of my TV shows in individual folders, but I don't group episodes in seasons folders. I use Ember Media Manager for metadata and images. Here are the contents of a typical show:

Folder name:
Hammer House of Horror

Contents of folder:
fanart.jpg
folder.jpg
Hammer House of Horror.S01E02.SDDVD.mpg
Hammer House of Horror.S01E02.SDDVD.nfo
Hammer House of Horror.S01E02.SDDVD.tbn
tvshow.nfo

As it was explained to me, without episodes in individual seasons folders, fanart won't get displayed on the Overview tab.  I'd love to see a solution for this.

Also, now that there's a separate BOXEEHACK option screen in Settings, I'd love to see an option to display TV Show fanart on the All Seasons and Individual Seasons screens.  While I'm not really interested in season specific fanart, if you enabled this request, I'm sure some folks would love to see that implemented as well.

Thanks for you hard work!

**Comment by boxeehacks** [comment]
I think I have found a way! :)

**Comment by KevinSartori** [comment]
Looking forward to it!

**Comment by boxeehacks** [comment]
Done :)
