### ISSUE TITLE
[Question] went back to stock?

### ISSUE THREAD

**Issue by boxeeboiler** [boxeehacks/boxeehack#305]
hi folks - i was able to install successfully as per instructions.  after which:
1) i removed the USB drive
2) put the hostname back to "boxeebox" as its easier to use

and now i notice i have gone back to stock automatically.  could it be that the hostname should stay as was suggested before the install? just trying to understand the requirements here as its written clearly that the USB stick can be removed

thanks

**Comment by D34dmeat** [comment]
Yes after install the hostname hack is changed to point att the new boot.sh wich starts the mod so if you remove or change it it will boot to stock as usual

**Comment by D34dmeat** [comment]
If you remember the path just change it back, the files are still on your boxee box, otherwise just redo the install

**Comment by boxeeboiler** [comment]
thanks! i did a reinstall and back to normalcy.  i think i over thought
this...even though technically the ";sh....." is appended to it, i am still
able to use the boxeebox hostname

**Comment by boxeehacks** [comment]
Yes, the hostname change is required for the hack to run. Nothing we can change about that. So just keep it in there :)
