### ISSUE TITLE
DTS Auaudio downmixed incorrectly when using TV speakers - voices far too low/action far too loud

### ISSUE THREAD

**Issue by homewoods** [boxeehacks/boxeehack#312]
Hi Guys,

Great work on the development.

There is an issue logged with boxee, which I was wondering what your take on it was.

Basically downmixing audio from 5.1 to 2 channel over hdmi to tv speakers, seems to mess up the audio levels, below is the jira boxee development link to the issue.

If you audio out to a soundbar or surround sound of course is fine, 

http://jira.boxee.tv/browse/BOXEE-11595

Let me know your thoughts?

Cheers

Rob

**Comment by boxeehacks** [comment]
Unfortunately this is part of the Boxee executable. We cannot make any modifications to the core way Boxee handles video and audio formats. Fixing these things would require recompiling the Boxee executable and for that a specific Intel SDK is required which we don't have access to.

**Comment by homewoods** [comment]
Thanks for your response BoxeeHacks. If you ask Intel would they not provide you the SDK or is it possible to replace the Boxee executable with a new XBMC version?
