### ISSUE TITLE
Remote control stops working after installing boxeehack

### ISSUE THREAD

**Issue by MappingPioneer** [boxeehacks/boxeehack#313]
After (successfully?) installing the boxeehack, the remote control for my boxee box no longer works. Other functionality seems to be working fine, and I can still control the box through the Android Boxee Thumb Remote app.

**Comment by cardassian-tailor** [comment]
have you tried to repair it, test the battery, or on regular boxee firmware? 
http://support.boxee.tv/entries/325206-pair-boxee-remote

**Comment by MappingPioneer** [comment]
Thanks for the tip on pairing. That led me to search the boxee forums, which led me to this:

http://forums.boxee.tv/showthread.php?t=62082&highlight=remote+control

Once I shut down the box, unplugged it for a minute, and plugged it in again everything worked.

Thanks,

Jon.

**Comment by bru73f0rc3** [comment]
awesome, also resolved my remote issue. :+1: :)
