### ISSUE TITLE
Request:ability to scan for new shows 

### ISSUE THREAD

**Issue by tekkietekkie** [boxeehacks/boxeehack#315]
I use my boxee for tv shows along with sickbeard but even with boxee setup to scan hourly it stops adding new ones quite often unfortunetly. There are some cases where i download a show and i dont want it to scan the whole drive it takes to long so i end up going into files which is a pain. Could a option be added so when you go into Shows, pick a show like family guy for instance where you added the options for all watched / unwatched could you put a scan there that only did taht folder instead of the whole drive?

In my case i have the volume media shared and under ther i have TV\family guy\season x and they are stored there so maybe if it can scan the family guy folder oly it would be perfect ;)

**Comment by boxeehacks** [comment]
Unfortunately that would be very tricky to do, and isn't feasible right now considering the amount of work it would take. There is a new http server in 1.4.1 that supports most of the old XBMC http API functions that could be used to trigger specific folder rescans from Sickbeard itself. I'll update the documentation for it on the wiki soon, and maybe some enterprising dev can add this to Sickbeard...
