### ISSUE TITLE
No way to tell if Check for new version is working, or what to expect

### ISSUE THREAD

**Issue by Bargeral** [boxeehacks/boxeehack#321]
When I upgraded to 1.4.1 I was unsure that it was doing anything, I ended up clicking several times and only when I walked away did it finish and reboot on the new version. The new version found dialog should contain text to say - this may take a while, it may look like nothing is happening, here is how long to wait and what to expect - Better yet a download progress bar, but at least the description if that's not possible.

**Comment by d4yz** [comment]
your boxee box logo should turn from green to red.

**Comment by swetoast** [comment]
i agree with d4yz the light is a good enough indicator plus the new installer worked perfectly this time around no hassle updating boxee+

**Comment by boxeehacks** [comment]
Agreed. The red light isn't ideal, but for now should suffice. In the future will keep in mind and improve this, but will have to balance the time spent on this with all the other stuff...

**Comment by Bargeral** [comment]
Ah, my Boxee is behind everything. Love the RF remote, but missed the red logo.
