### ISSUE TITLE
Cant access boxee hard drive over my network

### ISSUE THREAD

**Issue by ffiliere** [boxeehacks/boxeehack#322]
I am using windows 7 and cannot access my boxee hard drive from my pc. Mine used to come up as boxee and now shows up as intelce and when i click on my boxee hard drive it says it is not accessable.  I am a total tard when it comes to dealing with networks will some one point me in the right direction to get this issue resolved. I tried to find it under closed issues and the only thing that came up was that it was an issue with windows 8 and to downgrade to 7. since i am using 7 i dont know what to do.

![boxee](https://f.cloud.github.com/assets/3106056/45449/c1b7a8ae-5785-11e2-8218-a6f0b36feccb.jpg)

**Comment by ffiliere** [comment]
Nevermind I got it fixed. I had accidentally changed the share workgroup in the boxee when i was updating the host name. Grrrr took me 2 hour to figure that out. then done 10 mins after i post for help. gotta love it

**Comment by jonassalen** [comment]
I have the exact same issue. Changed the setting for 'share workgroup' back to WORKGROUP but still nothing. Any pointers?

**Comment by jruck** [comment]
I'm having the same issue on Mac OS X 10.8.2
![Screen Shot 2013-02-15 at 10 25 51 AM](https://f.cloud.github.com/assets/2606818/161111/ff7604ce-7783-11e2-9974-78f87bb1498a.png)
