### ISSUE TITLE
Playback of file being downloaded

### ISSUE THREAD

**Issue by navigates** [boxeehacks/boxeehack#325]
Boxee is a great player and can also playback files that is still being downloaded. However there are a few fallbacks and observations which would be great if it can even be addressed.
1. When you start playing the file, the playback will only play until the amount of bytes when you started the download. For example, the mkv is 4 gb and you start playing the movie when its done to about 300 mb, the movie will play till 300 mb and STOP. Restarting the file with the resume option does not work untill the whole 4 GB is complete.
2. If resume option can be fixed while the file is being downloaded then that would be perfect.
3. If the file can continue to play as the download is faster then that would be perfect as well.

Since this is a feature request, I'm not sure if this is even possible to get fixed but just putting it out there for the dev's to see and get an opinion.

**Comment by boxeehacks** [comment]
There is nothing we can do about this, since this requires low-level reengineering of the Boxee executable. We don't have access to that due to missing Intel SDK which is needed to compile a new version.

See the Wiki for info on the issue.

**Comment by navigates** [comment]
Thanks boxeehacks for the reply. I thought so. you guys are awesome.

**Comment by war59312** [comment]
Yeah that would be awesome.
