### ISSUE TITLE
Screensaver and/or Fan Art info

### ISSUE THREAD

**Issue by JoeHennessy** [boxeehacks/boxeehack#327]
Can someone please give some detailed instructions on how to change the screensaver with the Boxee+ Hack 1.4.1. Also what are the other folders in the download used for? I only had to use the contents of the install folder for the update.
Thanks

**Comment by boxeehacks** [comment]
The screen saver works exactly as it did before installing Boxee+Hacks. The hack doesn't change anything related to that, and probably never will. For the other issues check the FAQ which explains this and much more in detail.
