### ISSUE TITLE
Back Button additional Functions?!

### ISSUE THREAD

**Issue by Kepners** [boxeehacks/boxeehack#328]
Could it be possible to have additional functions added to the the Back/Menu Button to allow for faster navigation.

One Press = Normal Back space.
two presses = Menu Bar Pop up.
three Presses = Home Screen

Or maybe a combination of presses to Home screen.

The reason i ask is that it sometime a real chore jumping around boxee - even to get to the menu screen. A short cut would be brilliant. I Noticed on the iphone app there is an "home" button...

Cheers
Keps

**Comment by badbob001** [comment]
I would favor a long press of the menu button to bring up the quick navigation menu (settings, watch history, home, etc). It's a major chore to get that menu up if you are very deep into the file explorer.

**Comment by Kepners** [comment]
Yes that would be the best way. One long press allowing for the menu window.

**Comment by saragusa** [comment]
+1. I'm totally agree..

**Comment by boxeehacks** [comment]
Sort of covered by #171 and #123. Planned to improve as part of 171 at least
