### ISSUE TITLE
Noticed Missing Front page icons.

### ISSUE THREAD

**Issue by Kepners** [boxeehacks/boxeehack#329]
I just installed the new 1.4.1 version of Boxee plus; and in doing so i noticed that all my original settings for the front page where missing from the previous install. 
So; i checked the settings and they were all still clicked (music and files)....

I found that restarting the software solved the problem. But I thought you guys should know there is that error on first install of your update.

Cheers
Keps

**Comment by boxeehacks** [comment]
Hi, this is a known issue which is due to the upgrade process. Changing the settings and restarting will (as you've noticed) make the problem go away.
