### ISSUE TITLE
Fanart grab issue

### ISSUE THREAD

**Issue by sphinxlady** [boxeehacks/boxeehack#335]
This is a confusing one.

Fanart is grabbed fine from shows on first scan of media but for newly added tv shows it tends to ignore them.
Del the thumb cache in boxee+ tools doesn't fix this but del thumbs from the boxee stock  setting sometimes does help.

Other times it just plain flat out refuses to grab art from certain shows like say last day of the dinosaurs in my collection

**Comment by sphinxlady** [comment]
Update.

Seems after 5 days it has finally decided to see the fanart for that show.
Odd but hey it did the job in the end.

**Comment by boxeehacks** [comment]
We're still improving on this and the fanart system in general. Stay tuned for future releases...

**Comment by saragusa** [comment]
Thankkss  hacks........
