### ISSUE TITLE
Issue: Navigating fast within boxee and pressing central button often results in multiple central button clicks

### ISSUE THREAD

**Issue by Kepners** [boxeehacks/boxeehack#337]
Issue: Noticed that Navigating fast within boxee and pressing central button often results in multiple central button clicks. Similar issue when using the keypad.

**Comment by antinode** [comment]
Your remote battery is probably almost dead. I had the same issue yesterday.

**Comment by boxeehacks** [comment]
Yes is almost certainly a battery issue. When the battery is almost empty a lot of button presses get duplicated.
