### ISSUE TITLE
How do i play the next video in folder?

### ISSUE THREAD

**Issue by kissbomben** [boxeehacks/boxeehack#338]
I have enabled "jump to last unwatched tv show"  but when i play and an episode ends, it just goes back to the folder.. help please, what am i doing wrong? I have tried to put all the packed episodes (.rar) in one folder, didn't work, i unpacked them in the same folder, didn't work. i'm outta ideas..

Best regards / Kissbomben

**Comment by tekkietekkie** [comment]
The jump to last is just to put it to the next one in line that you havent watched, not to open it, there is no way to jump to the next one but it is a good request.

**Comment by boxeehacks** [comment]
Yep, as @tekkietekkie mentioned, it does something else entirely :)

As far as auto-playing next video: see #15 and #116
