### ISSUE TITLE
Bootloop even when USB stick removed

### ISSUE THREAD

**Issue by bhageman** [boxeehacks/boxeehack#341]
After running the update, everything appeared to be working. Now, Boxee is stuck in a bootloop. I removed the USB stick and the reboots continue.

Any suggestion?

**Comment by sphinxlady** [comment]
Tried recover mode?

**Comment by bhageman** [comment]
How do I get to recover mode?

**Comment by sphinxlady** [comment]
Hold down the power button on the top of the box for 8-10 sec and you should boot into recover mode.

Do a factory restore and then update normal back to the last firmware.
Then you can load the hack normally and enjoy.

Unfortunaly the stock firmware is prone to doing stupid things like this now and then but where stuck with it.

**Comment by JGKos** [comment]
The factory restore will fix this, I just finished up with the same issue.  This worked perfectly.

JK

**Comment by scoobshub** [comment]
This has been happening to me too (several times). Can't understand why, and factory restoring every time is painful :(

**Comment by sphinxlady** [comment]
The stock firmware is based on xmbc  but its based on on a version that 10 or more years old.
So you got old code and boxee programmers who can't code worth a crap and you get  badly done stock firmware.

There is nothing really that can be done about that and the hack itself is sitting on top of it so its at it mercy.

**Comment by bhageman** [comment]
Thanks for the help everyone. Appears to be working after a factory reset.

**Comment by boxeehacks** [comment]
We'll try improving things in the future, but alas this is a bit the nature of hacking this way. We have very little control over how the hack happens exactly which is why it sometimes fails.
