### ISSUE TITLE
Cannot shutdown with 1.4.1

### ISSUE THREAD

**Issue by srednao** [boxeehacks/boxeehack#342]
Instead of shutting down it reboots with low screen resolution and strange colours. 
Trying to shutdown again only makes the same reboot.

**Comment by Kepners** [comment]
I believe this has been raised a few times and all threads have been closed. I am not sure what the outcome of any of the previous threads were. I guess we must assume it will be sorted out at the next update.

**Comment by srednao** [comment]
I saw that but there was no resolution (e.g. fixed in next release) so I added it to get some feedback if it is to be fixed or that it cannot be reproduced or something.

**Comment by srednao** [comment]
Oops, wrong button.

**Comment by srednao** [comment]
Some additional info. When using the reboot function the boxee behaves in the same way, the screen resolution and the colours change. And you have to 'hard' turn it off with the button.

**Comment by d4yz** [comment]
The current workaround is going to apps screen and then shutting down. Pretty much if you try to shut down on a screen that is using the fanart script is when it will just reboot instead of shutting down.

**Comment by F33db3ck** [comment]
Same issue here...

**Comment by srednao** [comment]
On the file screen or apps screen it starts to shutdown, gets to a black screen on the tv but that's it, the  logo on the boxee box is still litt. 
Trying to reboot from those screens does the same thing as earlier, resolution and colours all weird.

**Comment by jonathanq** [comment]
I just tried to shutdown from the main screen (with fanart enabled) and it rebooted each time instead of shutting down.  I switched the the TV Shows screen (which also uses fanart) and it shutdown on the first attempt.  Might just be when sitting on the home screen it won't shutdown.

**Comment by boxeehacks** [comment]
One additional question guys; is this with the fanart mode on the home enabled or not? Does that matter? I think it may be something in that that's preventing the proper shutdown from happening...

**Comment by F33db3ck** [comment]
Does not matter, tried every setting for the home screen.

**Comment by boxeehacks** [comment]
Ok thanks

**Comment by Kepners** [comment]
Ive just tried it. Within "apps" there is no fan art running and the boxee will close down. In film or TV it will not close down just reboot. The Home screen varies sometimes it closed down sometimes it reboots.

**Comment by Gordonflash** [comment]
I have the exact same problem as described above. Every time I try to shutdown from main screen it reboots. The only way to shut down is by pressing the button on the boxee box itself. I have fanart enabled but I actually dont have any fanart pictures yet. But with every movie file/folder I also have a movie.nfo and a folder.jpg file. I have different kinds of movie media like .iso, .img and .mkv.

**Comment by ldbrenes** [comment]
Same issue as described... also sometimes when I try to shutdown instead of rebooting it will hang on the power menu. using ver 1.4.2

**Comment by bone9** [comment]
Also can't shut down from remote but is fine on the box.

**Comment by Toliver182** [comment]
@boxeehacks can you not simply run a python script when the shutdown button is clicked that contains:

``` python
os.system('shutdown')
```

**Comment by coroners** [comment]
I have to force shutdown by holding the power button 9 times out of 10.  Reboot works as it should.

**Comment by boxeehacks** [comment]
This has been solved! The feature will be in the next release (1.4.6) coming out very soon

**Comment by Baek87** [comment]
thank you Mr Solitude! Damn the thing shuts down fast now!! :-D

**Comment by Toliver182** [comment]
@boxeehacks did you find a more elegant solution that mine?

**Comment by Kepners** [comment]
Yup! So much faster! Cheers,

**Comment by boxeehacks** [comment]
Similar to your solution Toliver (thanks for the suggestion!). However the shutdown command didn't exist, so had to search a bit through the various busybox modules to find the right one.

**Comment by srednao** [comment]
Thank you
