### ISSUE TITLE
YouTube app misbehaving

### ISSUE THREAD

**Issue by boxeeboiler** [boxeehacks/boxeehack#345]
youtube app is acting weird.  directional buttons are now controlling a cursor on the screen and not the menu.  pause/play button no longer work...i have manually use the directional keys to expose the on-screen pause/play bar, focus the cursor on it, hit middle button.

**Comment by boxeeboiler** [comment]
and now it paused and crashed.  not sure if its boxee+ but hasn't happened with stock.  for what its worth, this is not reproducible.

**Comment by boxeehacks** [comment]
Cannot reproduce this. Sorry about the issue's you're having. If you find a way to reproduce (or if other people have this issue, please add here and I'll reopen...
