### ISSUE TITLE
Unable to add smb source

### ISSUE THREAD

**Issue by kgranson** [boxeehacks/boxeehack#347]
I just added Boxee+ to my boxeebox.  When I added it I had no file sources.  I am trying to add a smb source.  The boxee box does not see my server, so I enter in the server info manually.  I also enter the username and password.  I am able to browse all of the shares available on my server but as soon as I try to go a level deeper into the actual share that I want to add, boxee just goes back to the initial dialog box for adding a smb source.  

I can't seem to get past this and I can't seem to be able to uninstall the Boxee+ software to get back to boxee to add the source that way to see if it's a problem with the boxee or boxee+ software.

**Comment by sphinxlady** [comment]
Reboot the boxee/router/ and smb source and that should fix the problem.

**Comment by kgranson** [comment]
Hey!  That seemed to work. Thanks!

**Comment by sphinxlady** [comment]
No problem.

**Comment by boxeehacks** [comment]
Cool :)
