### ISSUE TITLE
Improve slide show

### ISSUE THREAD

**Issue by apgr** [boxeehacks/boxeehack#349]
The implementation of the ken burns effect in the slideshow is currently not well done. The images are zoomed too high and then just bounce around inside some imaginary box like an od game of pong!  There should be gentle uni-directional pans and zooms.  Any chance this could b fixed.

**Comment by boxeehacks** [comment]
Unfortunately it doesn't seem to be possible without being able to compile the code (which requires a few missing SDKs). If at any point this becomes feasible I'll reevaluate this...

**Comment by pdk-dsk** [comment]
I guess there's a possibility to add a slideshow app which could be much better than current BB slideshow feature including 3d slideshow,kenburn effects and background music play much like the slideshow apps available on apple & other android devices.They have amazing GUI for such features....I hope this is taken care in the upcoming enhancements.....
