### ISSUE TITLE
Video Playlists with Shuffle

### ISSUE THREAD

**Issue by VathanEevin** [boxeehacks/boxeehack#350]
As requested on the official Boxee Forums...many times.

"While Boxee Box does support .m3u and .pls playlist files created on a PC, without the ability to shuffle said lists from within the Boxee Box GUI, this is very tedious. Please consider this improvement. At the very least, an option to shuffle video playlist playback should be included."

What would be even better is a 'folder' play option like WinAMP has, which could then be randomized for play by the Boxee.  Just select a shared folder and add all to play queue - no playlist required!

It would also be OK if the Boxee could queue items insitu for play if the above is not possible...with a shuffle/randomize option too of course.

I am mainly interested in this for my music video collection, but with slews of MP3's it would be just as awesome to be able to control them like WinAMP on a PC.

**Comment by boxeehacks** [comment]
This should be covered with issues #202, #138, #15
