### ISSUE TITLE
No Movies, Shows, or Music Icons after installing! Help?

### ISSUE THREAD

**Issue by KarmaMole** [boxeehacks/boxeehack#354]
I just found and installed Boxee+ - did the install as instructed. 

Initial start-up was slower than usual, but I'm guessing that's cause Boxee+ is configuring itself, etc - however, when it started up (and until now) - I have no icons for 'Movies', 'Shows', or 'Music' - and they don't show up in pop-up menu either. I've checked the settings, and in home-screen settings their icons are set to built-in. Tried changing that, but it doesn't help. 

I can still FIND my local content, by navigating to 'files' and then selecting the relevant sections on the left side-menu, but that's super-tedious :( 

And it now makes me ask - is there a way to undo and reinstall regular boxee firmware if I can't find a fix for this? (Yes, I should've checked that first, I know)...

**Comment by KarmaMole** [comment]
Okay. Sorry, just checked closed issues, and found out that restarting fixes this. Sorry for the trouble :)

**Comment by boxeehacks** [comment]
No problem :)
