### ISSUE TITLE
Next release......

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#355]
When the next release? ... Only a clue please.......

**Comment by war59312** [comment]
When it's done, is my bet. ;)

Yea they need a releases page, something like https://wiki.mozilla.org/Releases . ;)

**Comment by boxeehacks** [comment]
They however have a huge group of people working on it full-time! I am (mostly) doing this by myself after work hours, so I cannot really predict exactly when I have time. On the blog (http://boxeeplus.com/blog/) I try to provide regular updates on what to expect when...
