### ISSUE TITLE
FTP Source acces

### ISSUE THREAD

**Issue by eterpstra** [boxeehacks/boxeehack#356]
Hello,

I was wondering when it would be possible to use an external source such as FTP to the Boxee+ firmware.

Can you tell me something about a new release with the support?

**Comment by Kepners** [comment]
You can access the Boxee Drive. Is that what you mean?

**Comment by eterpstra** [comment]
No i meant tot use an extern al FTP source. So connect to an FTP server

**Comment by boxeehacks** [comment]
Never. If the Boxee Box does not support a specific type of file source, then we cannot add it. This is due to an SDK that we need to create this kind of low-level code to run on the Boxee Box, but we don't have access to that SDK and cannot get access to it.
