### ISSUE TITLE
can this boxee bug be fixed?

### ISSUE THREAD

**Issue by lkistenkas** [boxeehacks/boxeehack#357]
Hi!

Would it be possible to fix this bug in the original boxee software in the hacked version?

http://jira.boxee.tv/browse/BOXEE-8951

It's about the boxee api on boxee box not allowing access to the settings file. This causes apps (like bartsidee or navi-x) cannot save settings.

With kind regards,
Laurens.

**Comment by sphinxlady** [comment]
No this isn't hacked software but a overlay and some tweaks .
They have no access to the core firmware as that's closed to the public

**Comment by lkistenkas** [comment]
thanks for your reply, sorry to hear that, too bad..
