### ISSUE TITLE
Changing media view on one type effects another

### ISSUE THREAD

**Issue by Bakkoda** [boxeehacks/boxeehack#359]
Hopefully this isnt a duplicate. When I change movies to carousel view and then switch to Shows, carousel view carries over even though its not the view I have originally set.

It does not do it when going to the home screen and then to shows but navigating directly to and from one section to another carries over the view style.

**Comment by SendoX** [comment]
is with me so

**Comment by boxeehacks** [comment]
This was done intentionally actually, since I always use both in the same view :)

**Comment by Bakkoda** [comment]
Oh Ok. Its not a huge deal as the carousel is nice but with 500+ movies its just not an efficient way to navigate for the kids.
