### ISSUE TITLE
"Jump to last unwatched TV episode" doesn't work properly if you don't have Season 1 of show.

### ISSUE THREAD

**Issue by gadgetchnnel** [boxeehacks/boxeehack#360]
The "Jump to last unwatched TV episode" option doesn't work if you have the episodes sorted earliest to latest and don't have season 1 of the show. This appears to be due to the following code in boxeehack_setwatched.py:

```
        item = lst.GetItem(1)
        items = lst.GetItems()

        more = 1
        reverse = 0

        if item.GetSeason() == 1 and item.GetEpisode() == 1:
            reverse = 1
```

This checks whether you have the list sorted earliest to latest by whether the first item in the list is season 1 and episode 1, which won't work if you don't have season 1. 
A better way would probably be to compare the season and episode numbers of the first 2 items in the list.

**Comment by boxeehacks** [comment]
This has been fixed. Will be in next release
