### ISSUE TITLE
Removal of IP/Region Check-up for "native" apps like VEVO

### ISSUE THREAD

**Issue by felixekman** [boxeehacks/boxeehack#362]
If I can make a suggestion. Is there any way to enable apps such as VEVO in Europe that was previously available? I think there is a “region lock/lookup” or something in the firmware because the app itself will work and show up with a VPN.

**Comment by boxeehacks** [comment]
Unfortunately not something we can do; this is because the Boxee server manages what content is visible where. We have no control over that...
