### ISSUE TITLE
1.4.2

### ISSUE THREAD

**Issue by F33db3ck** [boxeehacks/boxeehack#363]
Wow, with the 1.4.2 the box is real slow now when playing a movie or serie and going back to the menu, selecting movies or series. The shutdown bug i still present. ;-(

**Comment by ldbrenes** [comment]
+1

**Comment by helgeim** [comment]
+2

**Comment by styt** [comment]
+2

**Comment by junkuhn** [comment]
+4 (+3)

**Comment by tobbewilson** [comment]
+5

**Comment by boxeehacks** [comment]
This is all known issues, and there are already many other issues added on github for this.
