### ISSUE TITLE
Display NEF file

### ISSUE THREAD

**Issue by langluc** [boxeehacks/boxeehack#364]
It's possible to add NEF codec to view RAW file from Nikon?
http://blog.crushedredpepper.com/nikon/raw.html

**Comment by Oolong666** [comment]
The DNG format would be nice too.

**Comment by boxeehacks** [comment]
Unfortunately any new file formats will require recompiling the main Boxee executable. This however is not possible because we need the SDK that is used to create it, and we cannot get access to it.
