### ISSUE TITLE
backdrop/fanart?

### ISSUE THREAD

**Issue by langluc** [boxeehacks/boxeehack#365]
can I use the file backdrop.jpg instead of  the file fanart.jpg?

**Comment by crax83** [comment]
if you modify boxeehack_grab_fanart.py i don't see why you shouldn't be able to.

**Comment by D34dmeat** [comment]
You could always ftp into your boxee box, find the file and edit it with notepad++, and put it back, works instantly.

**Comment by langluc** [comment]
greit, it's work!
