### ISSUE TITLE
Boxee Hangs

### ISSUE THREAD

**Issue by awolt** [boxeehacks/boxeehack#367]
Im currently on 1.4.1. When my Boxee screen froze, which it does sometimes, I just rebooted. When I rebooted it just came to the Boxee Box Loading page, freezes and the Boxee alternately flashes Green then Red. Rebooted many times - no change. Did a settings reset, no change. Factory reset does not work either - get error.

**Comment by warpech** [comment]
The readme says it clearly:

> Also make sure you are on the latest firmware (1.5.1)

So maybe that's the reason of your problems?

**Comment by boxeehacks** [comment]
You should be able to do a factory reset. If a factory reset doesn't clear this then it's probably a hardware malfunction unfortunately. If the Boxee Box freezes often this may also be a signal of a hardware overheating issue that was already present. Best thing to do is to unplug it, and leave the box unplugged overnight. Then plug it in and boot to factory reset mode, and make sure to also clear all settings. Then boot back into Boxee Box.
