### ISSUE TITLE
Boxee ignores orientation tag from iPhone in videos

### ISSUE THREAD

**Issue by pistachioofnuts** [boxeehacks/boxeehack#369]
Boxee seems to ignore the orientation tag from a lot of the iphone videos making them appear upside down in Boxee. Even though they look fine on the computer, on the iphone or any other devices smart enough to recognize the orientation tag. Any fixes in work for this?

**Comment by boxeehacks** [comment]
This requires low-level modifications to the boxee executable code. For this we need the Intel SDK for the box, which we don't have access to, and cannot get access to. Unfortunately this makes it impossible to change this behaviour.
