### ISSUE TITLE
Multiple VPN Profiles

### ISSUE THREAD

**Issue by csrster** [boxeehacks/boxeehack#370]
My VPN provider gives me access to multiple servers located in different countries. I would love to be able to switch between them quickly and/or toggle VPN on/off. This would require adding support for multiple distinct VPN profiles. A nice-to-have would be the possibility to group multiple profiles with the same login credentials, so that one could avoid having to type in the same username/password every time.

From a GUI point of view this could just look like a Radio Box list of vpn servers with a "No VPN" option to toggle off.

**Comment by styt** [comment]
this would be an awesome feature to have for us using VPN services.

**Comment by boxeehacks** [comment]
There are some future plans for VPN switching and toggling, and there is already another issue which it is managed in... Closing for now, but will look at it after the basic VPN functionality is done to see if this needs to be reopened.
