### ISSUE TITLE
"Jump to last unwatched TV episode" bug

### ISSUE THREAD

**Issue by oscahie** [boxeehacks/boxeehack#371]
This feature works mostly great, but there's a small bug. When you play the automatically selected episode and use the remote to abort playback, the same episode is still selected. However, if you let the episode play till the end so that Boxee exits to the TV show list by itself, then whatever episode is at the top of the list gets selected instead.

**Comment by boxeehacks** [comment]
We don't get any signals from Boxee back about when playback has stopped, so we don't know how we exit or even when we exit video playback. So whatever happens afterwards is just boxee's default behaviour which we cannot change...

**Comment by oscahie** [comment]
I don't think the issue is related to exit signals but instead to how the "last unwatched" episode is selected via scripting. My gut tells me something is off here because if I navigate into a show and then manually change the selected episode then the bug does not occur.

**Comment by oscahie** [comment]
In version 1.46 this issue is now occurring always after watching any episode, regardless of what triggered the end of the playback. You can actually see how initially the played item is still selected but about a second later the selection is moved to whatever episode is on top of the list. 

This feature as it stands now is pretty much broken. Or am I really the only one with such issue?

**Comment by oscahie** [comment]
Ok, I finally decided to look myself into this issue and managed to implement a workaround. I'm also refactoring the rest of the code around selecting the last unwatched item for better clarity and performance, soon will submit the patch.
