### ISSUE TITLE
Error: script failed!

### ISSUE THREAD

**Issue by begee08** [boxeehacks/boxeehack#372]
Went to play Abraham Lincoln Vampire Hunter (2012).mp4, the following error comes up and the Boxeebox reboots.

 Error script failed!:
 boxeehack_server.py

Tried from the newly added Home screen link, and from the Movies option, both the same.

Any ideas anyone?

I tried other .mp4 movies and they start up/seem ok.

I'm running 1.4.2

Cheers.

**Comment by boxeehacks** [comment]
This is a known issue and slated to be fixed in the next release. There are already many other open issues for this at the moment...

**Comment by begee08** [comment]
Thanks for taking the time out to answer my bug notice, and also your work and effort on this is really appreciated.
Look forward to your continued efforts!
Cheers
Brian
