### ISSUE TITLE
Request: Fix zoom & pan of photos in screensaver

### ISSUE THREAD

**Issue by zk1212** [boxeehacks/boxeehack#373]
This is a long waiting feature. can a fix to the zoom & pan of pictures in screensaver be added?

**Comment by adambiggs** [comment]
+1

Also, could the screen saver honor the same settings used for picture slideshows?

**Comment by wftl** [comment]
+1 
It would be great to actually be able to see the pictures in the slideshow. The sizing is completely nuts.

**Comment by boxeehacks** [comment]
Duplicate of #63

**Comment by boxeehacks** [comment]
Please use the search function before adding new issues ;)
