### ISSUE TITLE
Fanart and other detailed enhancements

### ISSUE THREAD

**Issue by Bierbeer** [boxeehacks/boxeehack#374]
Hi for fanart the following is maybe nice to add:

Fanart:

Fanart for different seasons of shows. Placing fanart.jpg in the seasons folder will display another picture for each season. When you're inside season1 or season2 etc. 
If selected all seasons, it shows and scrolls threw all of the fanart from the seasons folders with a delay (like homescreen fanart)

Multiple fanart with delayed view (like homescreen fanart which displays random fanart). Placing fanart1.jpg fanart2.jpg etc inside a folder will display the different fanarts with a delay and a transition animation like in the homescreen. Maybe some nice and different kinds of transitions?

Ive seen it on a WD media player which displayed different types of fanart pictures with cool transition animations.

Carousel:
Add a divider for the carousel view to indicate that your in the beginning or at the end of the sorting list.

Watch Later:
Jump directly to the configured option watch later category. Going to the watch later will automatically jump to the, for example, Movies category.
Maybe an option to disable the other categories in the Watch Later menu?
Or show all watch later files in an all categories view. So all watch later clips / shows / movies are shown on one page.

BoxeePlus:
Add a page on the website displaying the latest released version. Now we cannot really see beside from the boxeeplus menu in the boxee box which version is the latest released.

Add a menu button to the boxeebox homescreen to show a page with the latest Blog posts of the boxeeplus blog !

**Comment by boxeehacks** [comment]
These are multiple issues. Please add a separate issue for each request. Like this I cannot mark a specific request as done, in progress or planned or whatever which makes it very difficult to manage. Some good suggestions in here though!

**Comment by boxeehacks** [comment]
I've created all the new issues for this, so closing this one now...
