### ISSUE TITLE
covers do not populate/resets back to non hack mode/locks up at beginning of eps

### ISSUE THREAD

**Issue by Supastyles** [boxeehacks/boxeehack#376]
I want to start off by saying thank you very much for all your hard work, I love all you have done. On not going to just make suggestions of what you should do.

I have experienced occasionally these issues the covers will not load no matter how long you wait have to rebo

I have had to re enter the path as it reverted back to boxeebox without the extra string.  i reenter it and the hack comes back.

Finally when different episodes are playing it can take up 20 seconds to get the remote response

These are all occasional issues not all the time

**Comment by boxeehacks** [comment]
I'll look into these. Please in the future make individual issues per issue that you have. Then I can close/track/etc them separately.
