### ISSUE TITLE
Add Navi-X link for TV Shows in Home Menu, Not just Movies

### ISSUE THREAD

**Issue by darkmuncan** [boxeehacks/boxeehack#377]
Really like that you added the option for "Movies" in home menu to directly open Navi-x for those of us that have the app installed. I think that's great but I have a vast library of local movie files so I'd rather my Movies icon go to that. However, I use Navi-x almost exclusively for TV shows (at least until the day when you guys find some way to integrate TV shows with Fastpasstv.ms). I would love the option to change my "Shows" icon to directly open Navi-x. Is that hard to add in?

**Comment by DVDPlayer** [comment]
I have just made a code change that will replace your "FRIENDS" button with any of the current apps that have been set up as replacements for the "MOVIES", "MUSIC", or "SHOWS" buttons.  That way you can change your "FRIENDS" button to Navi-X and still have your "MOVIES" button for your local movie files.  I just need to figure out how to share it here ;-)  Chris.

**Comment by darkmuncan** [comment]
Thanks Chris, that would work great

Mark

**Comment by boxeehacks** [comment]
I've merged DVDPlayer's code into the current dev branch so that will be in the next release. I'm revamping the system more in the future though to allow adding custom apps in a more full-featured way...
