### ISSUE TITLE
Hauppauge 950Q Not being recognized

### ISSUE THREAD

**Issue by rocksash21** [boxeehacks/boxeehack#378]
On the normal boxee firmware it recognizes this device for Live TV, but it is not working for me so I'm wondering if it has to do with me being on boxee+? 

Here's a link to what I'm referring to as well. 

http://pierrehardwareblog.wordpress.com/2012/05/22/boxee-by-d-link-and-boxee-live-tv-are-they-kidding-part-2/

Thanks for your help

**Comment by rocksash21** [comment]
Is there any ideas on how to fix this issue?

**Comment by boxeehacks** [comment]
Boxee+ doesn't change anything related to the Live TV functionality. But I also don't have a LiveTV or Hauppage to test with so I can't be 100%. I've heard of others though that have had success with live TV and Boxee+.

If you remove the hack again, does the feature return? (just do an uninstall)

**Comment by rocksash21** [comment]
Mybuddy has 2 boxees. He just installed boxee+ and is having same issue now. Tested on his other boxee running the original firmware and It works fine.

**Comment by Jchromeo** [comment]
That's a little weird, because I have the 1.4.2 and I'm still watching live tv all the time.

**Comment by rocksash21** [comment]
thanks apparently it was a user error.....I had the 950, not the 950Q. The 950Q worked fine. sorry guys.
