### ISSUE TITLE
Better view fanart

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#38]
Either make it accessible as a fullscreen thing somewhere? Or maybe lighten the background. Though shouldn't impact readability of the text on the page.

Also look into what we can do to add it to the other views on the episodesview (without uglifying it ;) )

**Comment by ghost** [comment]
can you tel me how to get fan art to work it doesn't work for me I don't know why tried everything ??

Movies
 +- [MovieName]
 +- [MovieName].nfo
 +- [MovieName].mkv
 +- folder.jpg
 +- fanart.jpg

this doesn't work for me I have it like this 
 spiderman man file than
 spiderman.mkv
 spiderman.nfo
folder.jpg
fanart.jpg

doesnt work for me it shows not a fanart 
 tried 720p and 1080p fanart

**Comment by boxeehacks** [comment]
How are you accessing these files? Note that this is not supported when using Boxee Media Manager (which you shouldn't use anyway, because it limits you in more ways than just this).

**Comment by ghost** [comment]
I don't know what boxee media manager is but I have like 4 external hdd hooked up to boxee box than I exes the file trough my pc over the network than I go in like spiderman 2012 than I see spiderman.mkv and spiderman.nfo than I make a folder called folder.jpg in that folder I put the fanart.jpg of spiderman2012 than I go to my boxee box klik in the movie shows nothing only the cover and info cast etc but no fanart does not work ??? what am I doing wrong

**Comment by boxeehacks** [comment]
You shouldn't have a folder called folder.jpg. You should have an image containing the movie's poster image called folder.jpg, and in the same folder as the movie have a fanart.jpg image with the fanart.

**Comment by ghost** [comment]
tried that already doesn't work

**Comment by boxeehacks** [comment]
Just make sure you have _one_ folder which contains your .mkv file _and_ your fanart.jpg and it will work. Also note that fanart is ONLY shown on the "Overview" tab.

**Comment by ghost** [comment]
so I have this now spiderman2012
spiderman2012.mkv
spiderman2012.nfo
spiderman2012.jpg 

stil doesn't work ???

**Comment by ghost** [comment]
maybe the fan art is to big ?? 1280x720

**Comment by ghost** [comment]
and I know only on the overview tab it shows but still nothing or it is a bug or iam doing something wrong here

**Comment by ghost** [comment]
![Untitled](https://f.cloud.github.com/assets/3061517/16667/193c95e6-4848-11e2-8fb5-d7375db6291f.jpg)

**Comment by d4yz** [comment]
fanart must be named fanart.jpg, no exceptions. It looks like you named yours spiderman.jpg or whatever change that to fanart.jpg

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
doesn't work

**Comment by ghost** [comment]
![Untitled](https://f.cloud.github.com/assets/3061517/16695/897ccb12-484a-11e2-9483-643d57ef552c.jpg)

**Comment by ghost** [comment]
![IMAG0238](https://f.cloud.github.com/assets/3061517/16697/b5c41180-484a-11e2-9368-8d50a29fadcb.jpg)

**Comment by ghost** [comment]
![IMAG0236](https://f.cloud.github.com/assets/3061517/16699/c0f39c42-484a-11e2-8eda-f254e668268c.jpg)

**Comment by ghost** [comment]
I tried it with other movies doesn't work doesn't make any sense to me ??

**Comment by d4yz** [comment]
Did you restart the boxee after you made the change?

**Comment by boxeehacks** [comment]
Can you turn on showing file-extensions in your explorer window? I think the problem may be that you have "fanart.JPG" instead of "fanart.jpg". Also whenever you change the fanart you either need to re-identify the movie from the menus, or use the clear thumbnails menu option in Boxee+ settings.

**Comment by ghost** [comment]
clearthumbnail cache but that wil dele al my movie covers ? or not and what doe you mean by file extention and I don't have like fanart.JPG I have small letters fanart.jpg spiderman 2012 I rescand the spiderman movie nothing

**Comment by boxeehacks** [comment]
No it will only make sure they get re-loaded. Whenever the Boxee box tries to display an image it makes a copy of it in its internal memory; this is the thumbnail cache. It ALSO does this if a file doesn't exist, it then makes a blank image. So if you didn't have the file in the right place when you started, then it stores a blank copy in that thumbnail cache. And even if you fix the problem later, it will never try to reload that image, unless you first clear the thumbnail cache.

**Comment by ghost** [comment]
yes I did restard the boxee and I wil try not to doe the thumbnail cash thing

**Comment by d4yz** [comment]
Defintlly try the thumbnail cache

**Comment by ghost** [comment]
lol stil nothing did the thumbnail cash restarted the boxee box stil nothing bug ? can some one make a video this week or some time this month because it doesn't make sense anymore ??

**Comment by ghost** [comment]
already found out what I and you did wrong its not fanart.jpg its just fanart without the .jpg lol

**Comment by boxeehacks** [comment]
Well i can see that in your last screenshot your fan art file is called "fanart.jpg.JPG" which is _not_ correct. Please turn on "view file extensions" in explorer first before you do anything else.

**Comment by boxeehacks** [comment]
No it is WITH .jpg, but you have your windows set to hide the .jpg (it's still there though ;) )

**Comment by ghost** [comment]
is there like a auto scraper for network drives and thanks for the help :)

**Comment by boxeehacks** [comment]
No problem :)

You can use something like Ember Media Manager or ViMediaManager. Checkout the forums (forums.boxee.tv) as well, people can help you there with other suggestions for this.

**Comment by boxeehacks** [comment]
This issue is fixed. Will be part of the 1.4.0 release
