### ISSUE TITLE
Future Request :Add Subtitles to streaming movies from navi-x

### ISSUE THREAD

**Issue by urielp** [boxeehacks/boxeehack#381]
Hi,
please forgive me in advance if this is a duplicated issue,
but i there any option to add in the future the ability to add subtitle to movies on navix?
it seems that now every movie or a tv show that im watching through navix do not have such option at all.

thanks

**Comment by boxeehacks** [comment]
This has been requested before, but is not something we can easily do. It will require changes from the developers of the Navi-X app.
