### ISSUE TITLE
"Enter New Label" Popup on Homescreen

### ISSUE THREAD

**Issue by JasGill** [boxeehacks/boxeehack#382]
There is a popup whenever I go to home screen which say Enter New Label. I can enter a picture url there which shows up as home screen background, but that popup keep coming every few seconds. It started after the latest 1.4.2 version. Any idea how to fix it??

**Comment by boxeehacks** [comment]
Hmmm... I know what it's related to, but not why it's happening. Will look into it...

**Comment by boxeehacks** [comment]
Fixed. Will be in the next version
