### ISSUE TITLE
Request : make boxee send WoL during start/wake up

### ISSUE THREAD

**Issue by JaFRyd** [boxeehacks/boxeehack#388]
It would be great having the possibilty of making boxee send the magic package, during startup and wake up. Maybe also possiblity to run it on demand as an app if the boxee is on and NAS/remote computor is down.

**Comment by boxeehacks** [comment]
There is a possibility to add plugins to the Boxee Box after Boxee+ has been installed. See the Wiki on how to create such a plugin. If you create a WoL plugin and want it included contact me and I'll add it. This is however probably not something I will add as to the feature-set myself as I have no use for it, and cannot test it (my NAS doesn't support WoL).
