### ISSUE TITLE
1.4.2 Rebooting Issue from Home Screen. Will not close down.

### ISSUE THREAD

**Issue by Kepners** [boxeehacks/boxeehack#389]
1.4.2 Rebooting Issue! Its just started to not want to close down and reboot like the 1.4.1 issue From home screen.
Have to go in to one of the Options to get it to close down.

**Comment by styt** [comment]
I also experience problems with both shutdowns and reboots.

**Comment by junkuhn** [comment]
Me as well..

**Comment by boxeehacks** [comment]
Many issues for this already open. Please use search first. This is an issue that I'm working on and will try to fix soon.
