### ISSUE TITLE
VPN Autoconnect on Netflix launch

### ISSUE THREAD

**Issue by nicovdw** [boxeehacks/boxeehack#390]
I would like to request a new feature to have an option to automatically connect VPN when Netflix (and other VPN dependant apps for other regions) are launched, and the VPN is down.

This was not a problem previously, as the Netflix app did not show up when the VPN was down, but now that it can be persisted on the home screen, it would be nice to have Boxee bring up the VPN automatically when you launch Netflix from the home screen, especially for the kids.

**Comment by boxeehacks** [comment]
There are plans to have a way to (in the future) quickly enable/disable VPN on the popup-menu. Hope that that helps enough... See the other issues for this...

**Comment by hahnmg** [comment]
Any news on the shortcut? Many issues on that but can't find anything working.
