### ISSUE TITLE
Focus on stability instead of looks and cool stuff

### ISSUE THREAD

**Issue by tobbewilson** [boxeehacks/boxeehack#397]
I have been following Boxeehacks now for a while, reading almost every email i get about requested changes but i must say that i'm a bit afraid that the focus has changed from getting a stable Boxee Box to getting a cool one where you can do all kinds of stuff.

I personally think that you guys do a great job and so far i really like the Boxeehack but i think that my two Boxee's are responding much slower now after installing the latest version.

Even though i know that you guys are doing so much more under the hood than seen in these email i would just like to request from all of you to focus on stability first and cool stuff later, or even keep the cool stuff there but give me the option to turn it off in the settings if i don't want it.
Let's say the fanart stuff which is cool but i don't need it, let me have choice to turn it off completely because i suspect that this can slow the gui down in my case.

Keep up the good work!

**Comment by mysticisgod** [comment]
I agree. I've found much slower response times since latest updates.

**Comment by boxeehacks** [comment]
That's the intention. However such a big rewrite (which was needed for future features) always brings new issues. The focus now is on stabilising that, which makes it easier in the future to keep stable.
