### ISSUE TITLE
Option to increase SMB timeout

### ISSUE THREAD

**Issue by brouer** [boxeehacks/boxeehack#398]
To allow time for slow drives on the SMB server to spin up.

**Comment by boxeehacks** [comment]
SMB timeouts are handled by the BoxeeHal process. I've tried modifying the SMB settings, but BoxeeHal keeps overwriting and changing them. The other settings are in an area which we cannot change (read-only part of the disk) and the BoxeeHal cannot be replaced unless we get access to the Intel SDK which is required to compile code for the box. Unfortunately we cannot get access to that.
