### ISSUE TITLE
For some users the Boxee Box doesn't turn off properly anymore after installing the hack

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#4]

**Comment by boxeehacks** [comment]
This was related to an installer issue that wouldn't grab the latest version off github correctly.

**Comment by bone9** [comment]
How do I fix this problem? I'm a new user. Do I need to re download and install again? Thanks

**Comment by boxeehacks** [comment]
There is currently a different issue which has similar effect as this. However that is a bug in the software, and you cannot fix it, you just have to wait for the next version. See the blog for updates when that is out...
