### ISSUE TITLE
[SKIN] Purebox

### ISSUE THREAD

**Issue by coroners** [boxeehacks/boxeehack#400]
I gave skinning boxeehack a try with the help of SendoX. 

HOW TO USE SKINS
1. Connect to your Boxee via FTP.
Find out how to connect via FTP here if you don't know:
https://github.com/boxeehacks/boxeehack/wiki/FAQ
1. Download and extract this zip file:
   http://www.mjukt.net/wp-content/uploads/2013/01/purebox.zip 
2. Replace the "data" folder found in your Boxee root with the one you just unpacked and then reload skin via settings or reboot your Boxee. 

Have fun just wanted to share this first try with you all to show it's possible and more people should do it! PEACE

![Splash](https://f.cloud.github.com/assets/3317965/95568/f95c7e12-6674-11e2-88d7-58e5e9050a1b.png)

**Comment by Toliver182** [comment]
This really awesome

However we should really integrate this into boxee plus. So have menu options to change the theme.

It seems this way every time boxee plus increases the version the theme will have to be rebuilt.
Which is not really ideal.

Thoughts?

**Comment by Toliver182** [comment]
Also this seems like a dangerous idea... Replacing the whole data folder

The zip doesn't contain all the correct files for boxee plus this seems like it could and would crash boxee plus.

**Comment by coroners** [comment]
I am totally with you both a little skin system wouldbe iideal. Some people have adressed issues with taking to much time with looks but to implement the choice and make the process easier would be more then nice.  If I had more knowledge I wouldbe glad to  help develop but I can't do more than some graphics. Code wise I have no clue in depth. Thanks for the feedback and hopefully some kind dev has some ideas or thoughts on these ideas. Peace

**Comment by SendoX** [comment]
nice !!!

**Comment by Toliver182** [comment]
Ok just to update you. I have found away of packaging a whole skin into one file Which you can just swap out and reload the skin.

I'm going to test it tonight, the. Put a menu option in place to swap skins safely

**Comment by SendoX** [comment]
cool

**Comment by coroners** [comment]
Awesome news can't wait to do a really worked out skin.  Weekend just got even more fun.

**Comment by Toliver182** [comment]
Ok at the moment with this safe method not everything can be modified, mostly everything can! 
https://www.dropbox.com/s/uaat2mc7373s3hi/media.zip
here is all the artwork from the boxee box

please download this make your theme changes 
you need to replace the images in here with your themed ones using the identical name of the files you are replacing.

Share it with me a zip and i'll make a theme file. 

once i have tested it i will show you how to make a theme file and implement it. 

then we can move onto more complex themes.

**Comment by coroners** [comment]
Wow! This is gonna take some time. But we could make the boxee a whole new visual feast. I love the fact that we can now change dialogs, all the icons, loading, and everything else. But yah this is gonna take a while. And a lot of testing to see that all the stuff fits and so on! THANKS so much for doing this.

**Comment by coroners** [comment]
Think I am gonna tackle this by first doing a mockup of overall design and elements like I do with most interface designs I do from scratch. This is gonna be fun!

**Comment by Toliver182** [comment]
ok sweet, the single file method may not work, i cant test it for another few hours until i get home. however im sure that we can skin the app regardles. we may just have to use all the files.

**Comment by Toliver182** [comment]
things like the splash cant be in 1 file but i'll figure a way of doing it

**Comment by Toliver182** [comment]
Coroners, have you got twitter? I'm @tolvier182
I've tested my solution and it works well, still need to do the menu part of it. 

Hows your theme coming along. I want yours to be the one that I publish.

**Comment by coroners** [comment]
No active twitter I am afraid but I have started with the teaming and most of them are done. A lot of icons made from scratch as well.  Got some more stuff to complete before it's ready but mail me at coroners@gmail.com and I will show you where I'm at..
