### ISSUE TITLE
Wanted boxeehack!!!

### ISSUE THREAD

**Issue by saragusa** [boxeehacks/boxeehack#401]
No news of Boxeehack?!?!? Many weeks without releases......

Help!!!

**Comment by tobbewilson** [comment]
Many weeks!? You got the latest version?

**Comment by saragusa** [comment]
1.4.2??

**Comment by saragusa** [comment]
If you refer 1.4.2: 2 weeks= maaany maaany weeks !!!!!!!

**Comment by coroners** [comment]
Feel free to put some work into the development and be happy that boxeehack even exists.

**Comment by saragusa** [comment]
If i did do .... maybe! 
For now only my donation.....

Sorry...
friendly

saragusa

**Comment by coroners** [comment]
It's maybe better if you specify in a friendly tone what you are missing or think can be upgraded or changed.

**Comment by saragusa** [comment]
But surely.....
If my tone did not seem appropriate I apologize ... 
Mine was just a joke to laugh a little and nothing else ... 

P.S: 
however, the donation I made it really ....

**Comment by saragusa** [comment]
50 € for the precision ...

**Comment by coroners** [comment]
Hehe ok. Well I just get frustrated with people complaining. The net is full of trolls.  But hey.  I want more boxeehack fun to spice up the home entertainment aswell. Glad you weren't a regular hater. Bet every donation is well received.  Peace

**Comment by Toliver182** [comment]
This is not a forum. this is a place for reporting bugs and requesting enhancements.

**Comment by saragusa** [comment]
oopppsss ... An exception every now does not hurt though ....

**Comment by boxeehacks** [comment]
2 weeks without anything yes. And before those 2 weeks I specifically blogged about how I would be abroad for a while due to work and would not be able to work on it for a few weeks.

Talk about impatient! :)

**Comment by boxeehacks** [comment]
Back though ;) so let the fun resume...
