### ISSUE TITLE
ubuntu or linux and xbmc on the boxee box

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#402]
you can not load ubuntu or linux and xbmc on the boxee box?
though xbmc works on the xbox 1 why not on the boxee box?
The hardware ought to be sufficient
root ? here:
http://www.gtvhacker.com/index.php/Boxee

**Comment by Toliver182** [comment]
This is a huge task.

The boxee box will only load its own operating system. There is security on the bootloader that prevents anything else from being booted. 

A few people have tried to swap out the kernal while the system is running with no luck.

**Comment by SendoX** [comment]
Today you can hack everything. so why not the Boxee box.

**Comment by Toliver182** [comment]
because the bootloader is signed and it signature checks everything it loads. the development enviroment is provided by intel and is only given to those who take our a contract to develop and sell devices that use their intel ce chip.

**Comment by boxeehacks** [comment]
With this hack we cannot load anything until the Boxee main software has already started. This means anything like a custom Linux or anything similar is impossible for now.

Also compiling anything for the box requires a specific Intel SDK that's not available for consumers. This means we cannot change this core behaviour.

**Comment by quarnster** [comment]
> Also compiling anything for the box requires a specific Intel SDK that's not available for consumers. This means we cannot change this core behaviour.

Not true. It's a normal x86 Atom cpu running linux so regular gcc for example is fine.

**Comment by quarnster** [comment]
> With this hack we cannot load anything until the Boxee main software has already started.

Actually, only the hal needs to start with this hack so you could make your "boot.sh" script run for example `mount -o bind /data/hack/any_executable_you_want /opt/boxee/BoxeeLauncher` to launch that instead of the BoxeeUI.

**Comment by albznw** [comment]
No luck with this yet?
