### ISSUE TITLE
bricked

### ISSUE THREAD

**Issue by claudiuchetan** [boxeehacks/boxeehack#403]
Not sure if this is caused by boxeeplus.
Anyway, I've installed 1.4.2. Worked great for about 2 days. Then, when I started boxee, it seemed to have gone through a full reset, asking for my account, and all settings changed to defaults. The boxeeplus options were not present.

After that, the next day, boxee hang and after resetting it it went into error mode (green+ red blinking). Holding the power button for more than 5 seconds, starts boxee directly with the yellow led on, it shoes the loading screen for a few seconds, and then there's no more signal to my hdmi. I don't know of a way to access it anymore.

Any clues? Did something similar (lack of posibility to enter recovery mode) happened to anybody else?

**Comment by sphinxlady** [comment]
Thats not boxee+ but the firmware from boxee itself or a hardware failure.
Boxee+ is a overlay and has no access to the core firmware itself so its not going to brick it.

Have you tried going into recovery mode and doing a factory reset?

**Comment by claudiuchetan** [comment]
unfortunately i can't access recovery mode. i keep the button pressed, it starts with the yellow led, but after a few seconds my tv shows a "no signal" message. and that's it :(.

**Comment by sphinxlady** [comment]
I hope its under warrenty.

There is a problem with the black screen of death due to the firmware but that tends to have no effect on the led.
Yours sound like a hardware failure but if its under warranty dlink is very good at replacing them without much headache.

**Comment by boxeehacks** [comment]
This really sounds like a hardware problem unfortunately. Factory reset should always remove anything you may have hacked.

**Comment by claudiuchetan** [comment]
I've taken the box into service today. Hopefully they'll solve the recovery mode issue. Thanks for your feedback.

**Comment by boxeehacks** [comment]
Good luck!
