### ISSUE TITLE
[SKIN] Orange

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#406]
Orange Skin Boxee V.1.4.2

HOW TO USE SKINS
1. Connect to your Boxee via FTP.
   Find out how to connect via FTP here if you don't know:
   https://github.com/boxeehacks/boxeehack/wiki/FAQ
   
   Download and extract this zip file:
   http://ul.to/0wyz87bd
2. Replace the "data" folder found in your Boxee 
   root with the one you just unpacked and then reload 
   skin via settings or reboot your Boxee.

![orangeskin](https://f.cloud.github.com/assets/3018141/99694/091484e2-67ad-11e2-8b7b-bd370ed8583a.jpg)

**Comment by boxeehacks** [comment]
Probably a good idea to post this on the Boxee forums as well. I want to keep this list a bit clean as it's already a huge mess to deal with :)

Really cool that you're doing more mods and hacks though, but unfortunately will have to close this, to keep things sane for me ;)
