### ISSUE TITLE
Scrolling with a mouse

### ISSUE THREAD

**Issue by maudis31** [boxeehacks/boxeehack#407]
Is there any possibility to add scrolling from mouse? Sorry, my english is basic! Thanks for your good work! You save the Boxee reputation!

**Comment by boxeehacks** [comment]
How would that work? You want to plug in a mouse through USB?

**Comment by Toliver182** [comment]
You can plug ina mouse via USB. Or use a wireless mouse, you plug the transmitter/receiver into the USB on the boxee, it works like a charm. Except scrolling. I don't think this will be possible as it would require code changes in the boxee app

**Comment by boxeehacks** [comment]
Yeah have looked into this. But it requires both some low-level changes (which we cannot do) and a lot of skinning changes to support this.
