### ISSUE TITLE
"Watched episode" Icon

### ISSUE THREAD

**Issue by Qyles** [boxeehacks/boxeehack#417]
Hello, First of all, congratulations for all the work you're doing.

I would like to propose a new feature. When a tv episode is marked as watched it doesnt make any difference between a fully watched episode and an episode you stopped playing because you were sleepy. What I propose is to introduce a new icon (for example a yellow tick instead of the green tick) for every episode which hasnt been finished (or already finished, you can stablish that every episode with 20 seconds remaining, are marked with a green tick, otherwise marked with a yellow tick).

Thank you very much for everything you're doing.

**Comment by FabianMeul** [comment]
I've already requested a similar idea in #303 .
Best to combine these.

**Comment by boxeehacks** [comment]
Yep.. Moving discussion to #303
