### ISSUE TITLE
disable power-on sound

### ISSUE THREAD

**Issue by luisvera** [boxeehacks/boxeehack#419]
It would be great if you can add an option to disable the sound the boxeebox makes when turning on.
thanks for the great work!

**Comment by Toliver182** [comment]
The sound that is shown when the video plays?

this cannot be changes as it is loaded before any of boxee+ features

**Comment by boxeehacks** [comment]
Correct. this cannot be changed. Otherwise we'd already have a cool spiffy new animation there ;)
