### ISSUE TITLE
Audio Output via USB to external DAC

### ISSUE THREAD

**Issue by rcbruce** [boxeehacks/boxeehack#424]
is it possible to select & use an external DAC via USB?

As a Linux variant, I would think so.

(see below for why one might want to use USB over SPDIF)
http://www.thewelltemperedcomputer.com/Intro/SQ/USB_SPDIF.htm

(see below for a specific example of using a Cambridge DACMagic with (likely) Ubuntu 8.04)
http://www.audiomisc.co.uk/Linux/Sound1/SoundComputing.html

**Comment by boxeehacks** [comment]
Not possible. This requires low-level software access. We cannot compile and load kernel modules or drivers or much else at the moment. And it would also require modifications to the boxee executable to be able to reroute that audio. If it doesn't work out of the box then this hack is not going to be able to add this. This requires an SDK we don't have access to.
