### ISSUE TITLE
sabnzbd and sickbeard 

### ISSUE THREAD

**Issue by nbrennan0317** [boxeehacks/boxeehack#427]
I can't find get info about the plugins so I will ask. Can  I install sabnzbd on the boxee ? What about sickbeard ?

**Comment by whyyn0tt** [comment]
Check the official Boxee forums. There are apps for both I believe, and they'll have the repo's containing them.

**Comment by boxeehacks** [comment]
If you want an app to control these, then you should check the boxee forums. They have a section specifically for apps and app requests.

If you want to run Sabnzbd ON your Boxee Box. Then you can write a plugin for it using the Boxee+Hacks plugin system. There are example plugins in the repo. This however goes beyond the scope of this hack, and is not something we'll build ourselves.
