### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by bauersteve** [boxeehacks/boxeehack#428]
i did just like the instructions said but i dont see my music icon

**Comment by cigamit** [comment]
Did you check the options to ensure that the Music icon is enabled?  If all else fails, reboot.

**Comment by bauersteve** [comment]
I don't see where the music icon is. i have re-booted a few times. Here are some picks of what my screens look like. maybe with this it might help . From what i can see the upgrade work as my screen save said so..
![IMG-20130206-00079](https://f.cloud.github.com/assets/3467174/134117/88b685ae-70bf-11e2-93c5-d4282d3fc5d0.jpg)
![IMG-20130206-00078](https://f.cloud.github.com/assets/3467174/134118/8d1dd5b6-70bf-11e2-8e03-f7f22ed28ac0.jpg)
![IMG-20130206-00077](https://f.cloud.github.com/assets/3467174/134119/9085b174-70bf-11e2-9025-7f38259b05c6.jpg)

**Comment by cigamit** [comment]
Did you go into Settings and enable it?

**Comment by bauersteve** [comment]
Sorry but i don't see anywhere were to enable it. does my settings look Ok in the picks? i forgot to include this pick.
![IMG-20130206-00080](https://f.cloud.github.com/assets/3467174/134215/b4be0134-70c6-11e2-85ae-386bde523f78.jpg)

**Comment by bauersteve** [comment]
i just got it to work . thanks for trying. All i did is UN-installed the hack via the USB  and then Re-installed it and bam it is working.
thanks again.....
