### ISSUE TITLE
Add Record Feature To Live TV

### ISSUE THREAD

**Issue by Jchromeo** [boxeehacks/boxeehack#429]
I was hoping if possible to add record capability to the Boxee for boxes which also have the Boxee live tv tuner dongle. The dongle has the capability to record as well, which is one of its selling points when sold as the hauppauge 950q (which what the Boxee tv tuner is, just re-branded).
WD tv live, which has the live tv feature like Boxee, recently added this DVR feature to their boxes using the same usb tuner dongle.
This is the one major feature I think the box was always missing. I can't believe someone hasn't suggested this already,
Cheers and thanks for all the good work.

**Comment by cigamit** [comment]
I believe this would require modifying the Boxee code itself, which we don't have access to change.

**Comment by boxeehacks** [comment]
This is unfortunately not possible. Cigamit is right, it requires modifying core Boxee code, and we don't have access to the SDK needed to do so. Even if we did though, none of the devs I know working on this have a LiveTV so not likely this is going to be added.
