### ISSUE TITLE
Additional/Cleaned up Overlays

### ISSUE THREAD

**Issue by whyyn0tt** [boxeehacks/boxeehack#430]
I'd love to see a few additional overlays for movies. Two really important ones for me would be a Documentary overlay (maybe a camera or film icon?). and one for Stand-Up Comedy Specials (microphone, or comedy mask icon?)
I'm sure others have more ideas (family/kid-friendly, animated, etc).

Also, I'd like to see the 'Musicals' overlay fixed up possibly. It seems to apply to "Musical" AND "Music" genre. I have a few movies about music, that aren't necessarily musicals such as Pitch Perfect, No Room For Rockstars.

**Comment by SendoX** [comment]
this ????
![doku_on](https://f.cloud.github.com/assets/3018141/129469/c163fc92-6fde-11e2-9ae7-a0c6bdb0c647.png)
![doku_off](https://f.cloud.github.com/assets/3018141/129470/c55ee0dc-6fde-11e2-9b81-2aafcf1ab505.png)
![fun_on](https://f.cloud.github.com/assets/3018141/129471/c81abb7a-6fde-11e2-9fe3-4259c7187208.png)
![fun_off](https://f.cloud.github.com/assets/3018141/129472/caa68310-6fde-11e2-8c16-d21afa358ba5.png)

**Comment by whyyn0tt** [comment]
Exactly like that. What are those from? Or am I missing them somehow in Boxee+?

**Comment by SendoX** [comment]
i create this self
