### ISSUE TITLE
Feature request: Support for external audio streams in videos

### ISSUE THREAD

**Issue by tararam** [boxeehacks/boxeehack#431]
It would be useful to add and option to load external audio stream during video playback, similar to adding external subtitles. Some videos may have additional streams (in other language or audio format) in the same folder. There is no way to switch to them at the moment. The only option is to switch built in audio streams.

**Comment by boxeehacks** [comment]
This is unfortunately not possible, since it requires pretty low level access to changing the code. This requires an SDK which unfortunately is not available.
