### ISSUE TITLE
NETFLIX Brasil works in all devices, but Boxeebox

### ISSUE THREAD

**Issue by ducapedia** [boxeehacks/boxeehack#433]
Netflix work natively here in Brazil.. including local programation and contents. Works withou VPN in PS3, Xbox360, Web, Android, SmartTV,.... (https://signup.netflix.com/?locale=pt-BR)
But in Boxee the app doesnt appear in list to install. DLink Support says theres nothing to do, because NetflixTeam didnt licensed netflix by boxeebox outsite USA.
I dont know how this works, becouse, is not by local IP (else if, Netflix will didnot work in PS3, Xbox etc). Maybe by ProductID ? (when product pass by ANATEL aproval to sell here in Brazil they block these list of numbers sended to here ?)
I see in boxee config, inside "services" a NETFLIX ID or something.. could be by this too.. I dont Know.
What I said are, if you use VPN on Boxeebox only, the netflix APP will apear to install, but only work when you're under VPN.. and you'll only get Netflix USA (not the Brazilian one).
Thats not a issue from boxeehack, even in boxeebox original firmware this occurs. But, maybe some kind of hack in mentioned service inside config may resolve this ?

**Comment by boxeehacks** [comment]
This is a restriction in the Netflix app itself, and we cannot change this.

**Comment by kvz** [comment]
https://github.com/boxeehacks/boxeehack/issues/432#issuecomment-24948481
