### ISSUE TITLE
Subtitles on passive 3D tv

### ISSUE THREAD

**Issue by nielsgaastra** [boxeehacks/boxeehack#434]
Suggestion, I have no idea if this is possible.
I guess this is a passive 3D issue only but I am not sure.

Situation:
I regularly watch 3D movies on my Philips passive 3D television.
When I watch it from a 3D bluray the subtitles appear to have a slight difference of depth (without 3D glasses) which results in sharp & hovering subtitles in front of the movie.

When I watch 3D movies from my Boxee Box the subtitles are sharp (without 3D glasses), like a normal movie, which results blurry subtitles. My eyes can't focus on them while watching the movie.

I would like to see an option to activate subtitles, designed for passive 3D televisions.

**Comment by boxeehacks** [comment]
The 3D support (works the same for passive and active 3D) places all UI in a fixed position. The way this works is embedded pretty deep into the core software code. Unfortunately this means it isn't changeable by us. Changing this requires an SDK which isn't available to us.

**Comment by nielsgaastra** [comment]
That's a pity, thnx for the response!
