### ISSUE TITLE
Feature Request: Improve browser

### ISSUE THREAD

**Issue by ferranrego** [boxeehacks/boxeehack#437]
I think that the browser needs improve because now:
1. Is unstable.
2. Isn't possible close ads above the flash players because when i click [X] in the ad the browser go to another webpage.
3. Isn't possible use tabs.

Is possible install chrome in Boxee? This is good solution, IMHO. (Has flash integrated too)

**Comment by boxeehacks** [comment]
This requires changes to the Boxee code, which requires access to an SDK which we don't have. Unfortunately there is nothing we can do about this.
