### ISSUE TITLE
Feature request: Transmission/uTorrent remote

### ISSUE THREAD

**Issue by ferranrego** [boxeehacks/boxeehack#438]
I think that is good idea include in frame-app option to access to Transmision/uTorrent in remote of other computer.

With this is possible download films from BoxeeBox to another computer and access to this files with samba.

**Comment by boxeehacks** [comment]
This can be implemented as an app on regular boxeebox, and is not dependent on this hack. Please request this app in the developer forums on forums.boxee.tv
