### ISSUE TITLE
Watch Later - Not working

### ISSUE THREAD

**Issue by dmike3** [boxeehacks/boxeehack#44]
I noticed when the hack is enabled the watch later for movies doesn't work.

**Comment by boxeehacks** [comment]
This has nothing to do with the hack. The boxee servers have been quite erratic the past few days, and it also fails a lot of the time for non-hacked boxee boxes. Also none of the server-communication behaviour has changed at all, so we couldn't even affect this if we wanted too ;) ... at least not without an entire server replacement.
