### ISSUE TITLE
FTP Transfer

### ISSUE THREAD

**Issue by sleepdebt** [boxeehacks/boxeehack#440]
Not sure if its possible, but am I able to FTP transfer files to the HDD connected to my Boxee? 
I can FTP in, see the drive, but when I transfer files I get a 500 error. Ive checked permissions on the MEDIA folder (777), so Im not sure what else to do.

**Comment by SendoX** [comment]
I use filezilla. make a new server and use the ip. settings/network/network/IP-address
click to media and here is you USB HDD

**Comment by boxeehacks** [comment]
Yes this works, and exactly as you described, however your HDD needs to be writeable for the boxee box, and the boxee box can only write on certain file-systems. E.g. NTFS is read-only I think. There is nothing we can do about that. If writing to that disk fails, check how it is formatted
