### ISSUE TITLE
update v1.4.5

### ISSUE THREAD

**Issue by SendoX** [boxeehacks/boxeehack#444]
The home screen is still not working. And where is the theming?
one but praise for the boxee that shuts down at last report. this works perfectly.
still a question. where else can i see what new things are there because with the updates? where is a home page for it?
thank you for the work that you are doing

**Comment by jampeef** [comment]
http://boxeeplus.com

**Comment by michske86** [comment]
Check out the blog at www.boxeeplus.com

**Comment by michske86** [comment]
@jampeef beat me to it :+1:

**Comment by Toliver182** [comment]
The theming abilities have not been added to this version it seems. 
@boxeehacks will be able to advise when he wants to add them to the main boxee+ I think stability of. The current feature set comes first

**Comment by SendoX** [comment]
ok right.stability comes first. but, i cant see on www.boxeeplus.com the versions number and the new features.

**Comment by boxeehacks** [comment]
@SendoX click the blog link. That always has the latest version along with release info on there.

Theming abilities haven't been rolled in yet. As mentioned stability first (and still have some ways to go there). After that new features. And the theming feature looks great, but I also want to review the code and make sure to refactor any things that are needed to make sure it fits in with the plans for future.

Since it's quite a big change it's not going in there before I've had enough time to check.

So ... it'll just take a while...

**Comment by boxeehacks** [comment]
By the way. What do you mean by "the home screen is still not working" what part isn't working for you?

**Comment by SendoX** [comment]
my homescreen
![812578_505957119446105_394395887_o](https://f.cloud.github.com/assets/3018141/143648/267d36fe-73bb-11e2-81f9-8a7c8f563d70.jpg)

**Comment by boxeehacks** [comment]
Can you go into settings, and change the "Home screen content" selection to something else? Preferably "Fanart". Then go back to your home screen. And then afterwards change it back.

I think it may be some settings file which is in an incompatible state for some reason. Changing this should set it back.

**Comment by SendoX** [comment]
I always setting the fanart. I have already uninstalled boxee +. then reinstalled. did not help. is not so bad. I always write about my home.xml. then my homescreen works again.
why you are building the home screen code is not firmly in the home.xml? After that affords to each his own homescreen. just as it does in the splash file.
i delete:
include>Common_Background</include
add:

texture>../720p/resources/background/Homescreen.png</texture

**Comment by boxeehacks** [comment]
Ok if you changed you Home.xml yourself then you'll lose those changes after an update of course, which seems to be what's causing this. In the future there will be a supported way to do custom backgrounds, but now you'll have to make the changes every time.
