### ISSUE TITLE
Flash player depricated

### ISSUE THREAD

**Issue by skipperbent** [boxeehacks/boxeehack#46]
Please update the flash-player inside the browser. 
When visiting sites as for instance gametrailers.com - you are prompted with a message: 

"Flash upgrade required - please visit get.adobe.com/flashplayer for the latest version".

**Comment by boxeehacks** [comment]
This unfortunately is something we cannot do. A newer flash player plugin that is compatible with Boxee simply doesn't exist yet. Boxee has indicated that an update will come somewhere in the next few months (don't know when) with an updated flash player. If and when that happens we will update the hack to either become compatible with the new Boxee version, or port the new features back into the hacked version.
