### ISSUE TITLE
Boxee 1.4.6 does not scan new sources

### ISSUE THREAD

**Issue by MonkeyWeiti** [boxeehacks/boxeehack#473]
Since the upgrade to 1.4.6 my boxee does not scan my sources.

I bought a new NAS which was working fine in 1.4.2, since the upgrade to 1.4.6 and a switch to SMB Protocol, boxee wont scan my source.

I tried AFP and SMB, also I tried to manually identify the folders. Boxee scans, shows up correct metadata but they wont get applied.

Watching movies and tv shows works fine over files, so I think there shouldn't be a permission problem.

**Comment by whyyn0tt** [comment]
Was having the same issue earlier. This worked for me:
With your sources already added, clear all media info from library (Settings>System>Advanced>"Clear media from the library...".  Let the Box restart.  It should begin scanning and verifying files at the bottom of the screen in the File Sources menu.

**Comment by MonkeyWeiti** [comment]
That did the trick!
Thank you very much...
