### ISSUE TITLE
SMB adding a share returns to add source menu

### ISSUE THREAD

**Issue by mk262** [boxeehacks/boxeehack#492]
Hello,

I'm running 1.4.6 on my boxee box.  When I go to add my smb share (which is readable from other set top boxes and PCs), I enter my PC name ('c8') and login info and am brought to all the shares on my box.  When I select any of them, there is a short delay and then it returns me back to the add source menu as if I wasn't doing anything.  I've also tried it with my PC's ip address instead of name, didn't help.

My box is wired and my shares are readable by 'everyone'.  I've tried clearing my media library already.

If anyone could offer a suggestion I'd really appreciate it.

Edit: I've already restarted the boxee box, my router, and my pc.  My windows firewall is disabled.  This is windows 8 and I've already opened up all the network sharing settings (network discovery, etc).

**Comment by jampeef** [comment]
sounds like a permission problem. did you add the username / password to the smb share in the boxee box?
maybe set folder permission on the share folder read & execute for the user group

**Comment by mk262** [comment]
I messed around with my permissions and eventually it worked.
