### ISSUE TITLE
More robust installation process

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#50]
Improve regexp's in sed commands in installer

**Comment by jerbob92** [comment]
sed -i 's/<hostname>(.*)<\/hostname>/<hostname>boxeebox;sh \/data\/hack\/boot.sh<\/hostname>/' /data/.boxee/UserData/guisettings.xml

sed -i 's/"hostname":"(.*)","p/"hostname":"boxeebox;sh \/data\/hack\/boot.sh","p/' /data/etc/boxeehal.conf

**Comment by boxeehacks** [comment]
Fixed! Did a lot of testing, and is now very robust. Also keeps your existing hostname in tact.
