### ISSUE TITLE
Boxee reboot resets all user and index data

### ISSUE THREAD

**Issue by forby** [boxeehacks/boxeehack#507]
This only started happening recently, but every time my boxee reboots I lose some part of my user data and have to go through the Boxee setup tutorial again.  The first time triggered the setup process, but kept my username and indexed media.  This last time, after a reboot, the entire thing seems to be wiped clean -- all data gone.  Now I'm kind of afraid to reboot again, though it needs it to keep from slowing down occasionally :)  

This is on the latest 1.4.6

**Comment by jampeef** [comment]
maybe corrupt databse. could perhaps do a factory reset and see if it helps

**Comment by forby** [comment]
yep, had to reset completely.  thanks!

**Comment by sleepdebt** [comment]
this has happened twice to me since ive installed the +hacks; both times it reset the system back to factory and i had to start from scratch with prefs and then installing the +hack again.

any fix for this?

**Comment by forby** [comment]
The Reset Settings option seemed to work for me:

http://support.boxee.tv/entries/20778533-Boxee-Box-Recovery-Console

I had to add everything once more, but I was used to it by that point :)
