### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by dmike3** [boxeehacks/boxeehack#54]
I'm not sure if this is just me, but I'm getting and unexpected error when trying to launch the browser.

**Comment by diff3** [comment]
I hade the same error then I mounted whole opt/boxee insted of just the skin dirs. Then I changed back to just skin dirs it started to work again.

**Comment by dmike3** [comment]
I fixed the issue by simply disabling the hack running the browser and re-enabling the hack and running the browser again.

**Comment by dmike3** [comment]
The problem is back again.. hrm..??

**Comment by boxeehacks** [comment]
Boxee+ is mainly a skin over regular Boxee, with a few buttons added that start python scripts that add some functionality. However the builtin functionality (such as the browser) cannot be changed by us. Such weird behavior in the browser is a Boxee bug, and is also present without running the hack (I've previously seen it many times). Note also that starting the browser is like any other app, and depends on the Boxee servers operating properly, which the past few days they have not done. Like that is related to these stability issues. Closing for now, and let's see if this is still present after we have our server replacement (more on that soon)

**Comment by boxeehacks** [comment]
I think I found what this issue was... Will fix it in an upcoming update

**Comment by boxeehacks** [comment]
In all my cases it was due to a font that was missing... fixed now...
