### ISSUE TITLE
Enhancement: Sort filelist by date

### ISSUE THREAD

**Issue by mrplow** [boxeehacks/boxeehack#55]
My wife always asks what the latest shows we have are I always go to shows then sort by recently added. But if you database gets hosed the recently added sorting gets borked, as one would expect it to. It would be nice to be able to go to files and sort it by filedate. This would also be useful for photos because different cameras have different file naming schemes.

**Comment by war59312** [comment]
+1 Drives me crazy after doing a new complete scan (normally to fix bugs, like broken or incorrect thumbnails).

**Comment by jerbob92** [comment]
Not sure if (currently) possible, I'm quite sure this is in the Boxee binary.
I do plan to replace the homepage videos with your recent library additions.

**Comment by scoobshub** [comment]
@jerbob92 having recent library additions in the homepage would be AWESOME. Do you think this will be easy to add? (Many thanks for all your work, the subtitles manager is fantastic!)

**Comment by jerbob92** [comment]
I'm not sure. There is one good thing: the url it uses now is coded into the template, so we can edit that easily. 
It's some rss:// url, so we need to find out how to create our own.

**Comment by dmike3** [comment]
This would be an awesome feature. Another step away from Boxee's server plus making it a better system.

**Comment by jerbob92** [comment]
Homepage featured being replaced is done: #60

**Comment by boxeehacks** [comment]
Yeah looked into this today, but the sort-modes are quite limited in the Boxee executable. Will enable everything we can, but don't expect much from it unfortunately. There are some things we might be able to do in python, but it won't be very efficient probably. Closing for now...
