### ISSUE TITLE
chown missing

### ISSUE THREAD

**Issue by mrplow** [boxeehacks/boxeehack#56]
easy peasy to include this bin which might be helpful to others

**Comment by diff3** [comment]
I belive you got chown in busybox. So you can do soft link to it. 

ln -s /data/hack/bin/busybox chown

I hope it work in BB this worked on my ubuntu 12.10 distro. (ln -s /bin/busybox chown)

**Comment by boxeehacks** [comment]
Chown does indeed exist in the extended busybox we added to the Boxee Box. So you can just type "busybox chown whatever". However the Boxee Box only runs as root ever, and there is no multi-user functionality part of the custom firmware. /etc/ is on a read-only part of the firmware, so things like adduser and addgroup will not work. So I'm not 100% sure what the point of having chown would be...

ln -s /data/hack/bin/busybox /data/hack/bin/chown

That'll do the trick on the Boxee Box.
