### ISSUE TITLE
custom thumbnails??

### ISSUE THREAD

**Issue by rocksash21** [boxeehacks/boxeehack#578]
I know how to add fanart but was just wondering if there is a way to manually add a thumbnail for cover art? Some movies either can't be found or just have the wrong thumbnail art. Thanks

**Comment by sumo300** [comment]
Boxee+Hacks supports the [XBMC NFO](http://wiki.xbmc.org/index.php?title=NFO_files) file.  So, grab [MediaElch](http://mediaelch.kvibes.net/) and you can download and set the poster and fanart using the defaults or whatever image you'd like.  Then, either re-identify each movie you've added an NFO for or clear everything and have the Boxee find it again.  It should use the NFO by default, but will ignore it if it has already discovered a movie and cached its info.  There's also a setting to allow the fanart for all of your movies to be randomly displayed on the main screen.  This was one of the features added to Boxee by this hacks project before it was abandoned.

**Comment by rocksash21** [comment]
Thx Sumo....that was a good workaround and fixed my issue. Wish there was a way to just change the thumbnail without having to dload a whole program but it did the job. Thx again!!
