### ISSUE TITLE
Add Audio Delay (offset) settings

### ISSUE THREAD

**Issue by maty974** [boxeehacks/boxeehack#59]
If this enhancement can be done #57 (Add Audio Output device settings to be set to Airplay capable devices)

It will be really really useful to have this Audio Delay settings available, because when streaming audio to the Airport Express, the delay must be set to something like 1,600s.

Like the XBMC settings here:
http://wiki.xbmc.org/index.php?title=Video_playback

thanks if this can be implemented !
and congratulations for your works on this boxeehack ;)

**Comment by jerbob92** [comment]
There already is a sound delay option in boxee...
