### ISSUE TITLE
Back to oringinal software

### ISSUE THREAD

**Issue by royalleader** [boxeehacks/boxeehack#605]
Hello. Is it possible to go back to the orignial boxee software exactly as it is now if I install the boxee+hack and don't like it? If so, how? Thanks.

**Comment by chimeraxp** [comment]
Yes remove string enter in host reboot and done

**Comment by royalleader** [comment]
So I just have to remove that string and when I restart it will be automatically be restored to its original state? Also does that mean it is installing boxee plus everytime it restarts and increases the start time?

**Comment by chimeraxp** [comment]
Only installs once , the changes the string to boot .

**Comment by royalleader** [comment]
Okay, thanks. I have installed it now and will try it out if I want to go back... looks pretty good so far.
