### ISSUE TITLE
Photo Screensaver Fix

### ISSUE THREAD

**Issue by Silent337** [boxeehacks/boxeehack#63]
Is it possible to remove the pan and zoom effects on photos displayed in the screensaver? It would be good if the settings applied to the slideshow were mirrored in the screensaver.

**Comment by boxeehacks** [comment]
Will look into this.

**Comment by Silent337** [comment]
Thanks. I appreciate all the work you are putting into the updates. It has restored my hope that the box could achieve its full potential, or close to it.

**Comment by boxeehacks** [comment]
These are two separate parts of the binary code. The screensaver part doesn't have any settings anywhere for this. Unfortunately until we can compile our own, this means this is not possible...
