### ISSUE TITLE
Make filename readable in movie details page

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#65]

**Comment by gadgetchnnel** [comment]
Something to consider with this is that, if a file is from a network share, the path may contain the password used to access the share. The skin file boxee_media_action.xml uses **ListItem.pathtoshowinmediaaction** which is truncated and has the password masked out. **ListItem.Path** is not truncated but also doesn't have the password masked out. This password masking would need to be replicated to avoid displaying the password on the screen.

**Comment by boxeehacks** [comment]
I just put in the Listitem.filename which is a lot cleaner and a lot nicer.
