### ISSUE TITLE
Rename my music to music, dutch translation does not fit homescreen

### ISSUE THREAD

**Issue by kroondomein** [boxeehacks/boxeehack#7]
In the homescreen THE my music is translated in dutch to mijn muzi...  
It cuts of THE last two letters. It would also be more compliant with THE other categories if there were no "my" in front.

No major issue of course ;)

**Comment by boxeehacks** [comment]
Will look into this. If there is a normal "music" field in the localization file, this should be an easy fix, and will change this this weekend.

**Comment by boxeehacks** [comment]
Fixed!
