### ISSUE TITLE
New Icon on dash for Music Concerts separated of Movies

### ISSUE THREAD

**Issue by felipesalomao** [boxeehacks/boxeehack#74]
We have 3 kind of video content: Movies (already have icon on dash), tv programs (also already have icon on dash), and music videos blu-rays like adele concert, coldplay concert, etc. We need add this icon to dash and separe movies from music video blu-rays, actually when i click on Movies icon it mix Movies with Music Video blu-rays, do not make sense..

Like solitude said, these should be little dificult because it have to split movies in 2 categorys, 

First Category: to real movie like 007, batman, spider man, etc
Second Category : Music Videos like Adele Concert, Coldplay, etc

But i belive that on near future it should be possible.. Keep its up.. Thanks for all

**Comment by boxeehacks** [comment]
Unfortunately the way the hack works now we cannot change the structure of Boxee's database at all. This means we cannot do this. The best thing you can do to keep them separate is to add them as separate sources to your Boxee Box and in Movies select Sources and select the type of movie you want. I'm afraid that's the only possible semi-solution at the moment...
