### ISSUE TITLE
Writing subtitles back to the original video's folder?

### ISSUE THREAD

**Issue by boxeehacks** [boxeehacks/boxeehack#80]

**Comment by felipesalomao** [comment]
It would be great, for example: On default subtitle system, when we search tv show epsode subtitle, its find and works with subtitle but dont download subtitle srt file to tv show epsode directory, would be great download same name as video file, example, if i search subtitle for video file named as dexter s07e08.mkv, would be great download srt file renamed automatically to dexter s07e08.srt

**Comment by boxeehacks** [comment]
Sounds good. Will look into it...

**Comment by boxeehacks** [comment]
Unfortunately it turns out this cannot be done. The various folders don't get mounted via Samba, but accessed directly from Boxee. As such we have no way of writing to any share. The only possibility would be for locally connected (to the BB) harddisks, but this is quite a bit of effort for a niche use case.

If we ever get the option of recompiling the Boxee executable and getting into the guts of things, this may be reconsidered...
