### ISSUE TITLE
Adding Reboot to Shutdown

### ISSUE THREAD

**Issue by doolaik** [boxeehacks/boxeehack#81]
Can you add a reboot function to the shutdown menu?  Sometimes there are issues with audio and video that a reboot can fix, but it's a minor annoyance that there isn't just a one-click solution to rebooting already baked in.

**Comment by ScottAllyn** [comment]
There's already a reboot option in the shutdown menu; at least with versions 1.2.1 and 1.2.2 .

**Comment by jesseblue** [comment]
Its already added

**Comment by doolaik** [comment]
whoops, hadn't noticed it that.  thanks guys!
