### ISSUE TITLE
Media Flags

### ISSUE THREAD

**Issue by cmgfender** [boxeehacks/boxeehack#83]
Anyway to incorporate media flags into a movie or tv shows overview page?

Like studio and the like, but also source and quality?

**Comment by boxeehacks** [comment]
Not sure if we have access to this info, but I would imagine this would be possible. Especially studio I'd like to add. Now that everything is HD, it would clutter things up too much to add an HD label everywhere I think, but something more subtle might do the trick.

**Comment by boxeehacks** [comment]
After having looked at this a lot over the past few hours... It seems that this information is only partially available.

The studio info is available in the Boxee db, but the source and quality etc. aren't there. Maybe in the future we can add it back.

Here's an image of what it could have looked like ;)

![mediaflags.jpg](https://f.cloud.github.com/assets/2787942/2005/d4b545ee-4171-11e2-9f51-aff5d38321eb.jpg)

But alas, it wasn't meant to be. I'll keep this in mind and if this ever becomes possible may add it then. For now we have studio labels now (yay!) so closing this issue...
