### ISSUE TITLE
Request: Fanart for Movie List View

### ISSUE THREAD

**Issue by jesseblue** [boxeehacks/boxeehack#84]
Can this be done?

Thanks for looking into it...

**Comment by boxeehacks** [comment]
I was actually contemplating adding a new view mode which always shows fan art, but specifically optimised for it. Something similar to this:

http://s15.postimage.org/3uksg6vzv/confluence_xbmc_skin.jpg

But then Boxee-styled of course

**Comment by KevinSartori** [comment]
That looks good! My favorite skin for XBMC is Transparency, so I would to see a more "list" oriented fanart view:

http://xbmc.org/wp-content/gallery/transparency/4_movies-fanart.jpg

Transparency effects are awesome on a skin...

**Comment by jesseblue** [comment]
i didn't want to be a drag by requesting something so big but if it was possible, i'd gladly take that skin over the movie list view...i don't need any of the description info when choosing a movie so a full view of the fan art will be sweeeet...

**Comment by boxeehacks** [comment]
Done. Will be part of 1.4.0
