### ISSUE TITLE
Request: Option to Change Main UI Background

### ISSUE THREAD

**Issue by ScottAllyn** [boxeehacks/boxeehack#86]
I'd love to see an option to change the main UI background from within the Boxee Box. The Ambience plugin can do it, but the change is not saved on reboots.

**Comment by hessius** [comment]
I'd love it if it could display a random fan art picture or even a slideshow. Maybe it would be easier to allow the user to specify a folder from which a random pic would be chosen and it would be up to the user to populate the folder?

**Comment by boxeehacks** [comment]
Have already looked into this a bit. Fanart would be difficult (but probably not impossible) because we don't know for sure whether a movie has fanart. But something like this would definitely be nice!

**Comment by hessius** [comment]
Great!
Maybe if #23 was implemented (auto dl of fanart https://github.com/boxeehacks/boxeehack/issues/23) this would be a bit more feasible?
#23 seems a long way off right now so fanart home screens might have to wait until then.

**Comment by michske86** [comment]
Maybe if #150 was implemented this would be even a bit more feasible? Since you'll have a source that's dedicated to images then? (Which could be the same source as your movies, but just with scanning for images enabled, this way importing all the fanart...)
Just a thought :)

**Comment by SendoX** [comment]
![home3](https://f.cloud.github.com/assets/3018141/15415/8bb11e72-4761-11e2-8e0e-969cd04372b7.jpg)

**Comment by boxeehacks** [comment]
You can as of 1.4.0 in the home screen set the background to show fanart instead of the default background. I'm probably not going to add many other customized backgrounds because it would break the feel of the Boxee box somewhat I think. For now I think this will suffice...
