### ISSUE TITLE
VPN MTU tuning appears broken

### ISSUE THREAD

**Issue by recursivemonk** [boxeehacks/boxeehack#87]
The VPN MTU adjustment is not currently working under 1.2.2.  Just installed it for the first time about an hour ago.

After successfully booting with boxee+ I established my VPN connection and then checked the MTU through telnet with ifconfig and the MTUs were still at 1500 and 1496 for etho and ppp0.

I then tried manually invoking the network.sh script from telnet and it returns a syntax error on "fi", so I'm not sure if that is the source of the problem, but I kind of doubt it.

Anyways, I'm the poster from the boxee forums that confirmed the issue & resolution for MTU related VPN problems when a boxeebox is connected via PPPOE or a similar network connection.

The fix that I applied in a manual script simply executes:

ifconfig eth0 MTU 1460
ifconfig ppp0 MTU 1400

However, that script, or those commands, have to be executed AFTER the VPN connection is established.  

Since the VPN has to be manually invoked through the boxee UI, your network.sh script won't have any effect if it only runs at startup.

I would suggest one of two solutions:

1) Add an option to the Boxee+ Tools menu to invoke an MTU script that tunes the eth0 to MTU 1460 and ppp0 to MTU 1400.  

2) Create a more clever programmatic method so that the script is somehow automatically invoked after ppp0 is established.  How you would do that, I honestly have no idea

My recommendation is the first approach.  It should be a simple and easy fix to implement.  It means the MTU is manually set only by those who need the function and it is left untouched by those who are not affected by VPN MTU issues.  

That being said, Boxee's default MTU of 1500/1496 for the ppp0 doesn't conform to the IETF RFC....so overall  it would be best to fix it for everyone even though some are not affected by the bug.

**Comment by jerbob92** [comment]
We should be able to replace "/etc/ppp/" with our own, and then edit the ip-up/ip-down script to set the MTU.

**Comment by recursivemonk** [comment]
I thought about that myself, but couldn't figure how to get around the fact that etc/ppp is read-only.  If there is a way to replace it with our own that would be the proper solution I would think

**Comment by jerbob92** [comment]
The same way we replace everything. We copy it to /data/hack and then replace the original folder with a remount from /data/hack. Like this:
cp -R /etc/ppp /data/hack
mount -o bind /data/hack/ppp /etc/ppp

**Comment by boxeehacks** [comment]
That's a much better way of doing things. And should be pretty easy to implement.

**Comment by boxeehacks** [comment]
Putting it in the next release

**Comment by recursivemonk** [comment]
so i've manually tested this...if you do the copy as jerbob92 above suggests that works fine, then i edited the ip-up script and simply reset the mtu like this:

code excerpt:

  route del default ${PRIMARY}
  route add default gw ${SERVER} dev ${TUNNEL}
  ifconfig eth0 mtu 1460          # here we adjust the MTU down from 1500
  ifconfig ppp0 mtu 1400         #  here we drop the VPNs MTU back to 1400 for stability

Then I changed network.sh so that upon reboot it just executes the bind again:

mount -o bind /data/hack/ppp /etc/ppp

This all seems to work nicely now.  However, being a pretty terrible programmer/script writer and n00b to github, I'm not sure how we could execute all of this into the boxeehack.

Do we write something into the install script so it does the copy and modifies the code after it does the copy?

Or should we simply have our modified ip-up script get copied down from github during installation?

Honestly, I'm not sure which is 'the right way' or how to do either.

**Comment by boxeehacks** [comment]
Yes, the easiest way is to just package in the modified ppp scripts, and mount them over the old ones. I'll add this in the new release...

**Comment by recursivemonk** [comment]
excellent!

**Comment by boxeehacks** [comment]
The MTU tweak will be in the new version. Still working through some stuff with the shortcut though, so that'll be a later version unfortunately...

**Comment by boxeehacks** [comment]
The shortcut is in a different pull request, so will continue the discussion for that part there...

**Comment by recursivemonk** [comment]
Unfortunately, the modifications that you made aren't working.  This is now in a new issue https://github.com/boxeehacks/boxeehack/issues/149
