### ISSUE TITLE
Update/News Notification

### ISSUE THREAD

**Issue by coyote4til7** [boxeehacks/boxeehack#91]
I don't see a way on the website to be automatically automatically notified of news and significant updates. It's not a software feature as such, but having an RSS feed/email subscription/whatever makes a big difference in making us forgetful users stick around and update to new versions.

**Comment by boxeehacks** [comment]
Over time I will expand the website significantly. Merge in the FAQ and some other stuff there. Add a blog with updates as well. RSS feeds. Video tutorials if needed. Etc. etc. I'll put this on my todo list for that, but closing it here to keep this focussed on the boxee box itself...
