### ISSUE TITLE
Add Torrent Client

### ISSUE THREAD

**Issue by maty974** [boxeehacks/boxeehack#94]
maybe it's just utopic, but I try :)
It could be very very useful! ( like what it was in the previous version of Boxee on MacOSX )...

**Comment by hessius** [comment]
Someone did this over in the forums at forums.boxee.tv: http://forums.boxee.tv/showthread.php?t=63987 & http://forums.boxee.tv/showthread.php?t=63248&page=21&p=283508&highlight=utorrent#post283508

This user got utorrent. In the interest of using as little resources as possible Transmission's daemon version might be better? http://www.transmissionbt.com/

On a side note: For this to be useful, at least for me, the client will have to be able to save files to a NAS

**Comment by enguel0314** [comment]
+1

**Comment by moiristo** [comment]
uTorrent seems to be the most easy way to go, but you do need to package the library files described in the thread, as the libgcc of the boxee is too old: 

```
ld-linux.so.2 
libcrypto.so.0.9.8 
libgcc_s.so.1 
libpthread.so.0 
libssl.so.0.9.8 
libc.so.6 
libdl.so.2 
libm.so.6 
librt.so.1 
libz.so.1
```

Can someone supply these library files from a 32bit linux installation?

**Comment by moiristo** [comment]
Note that libssl and libcrypto 0.9.8 are not strictly necessary, there are 1.0.0 versions in /lib, which can be symlinked as the 0.9.8 versions

**Comment by diff3** [comment]
I got utorrent working, I'll zip my files

**Comment by diff3** [comment]
It's not pefect but it's working. If you can sort out all bugs it would be great. At the moment you can onlys use the config file, you cant do any configurations from the webpage. Whats why I delete all dat files and old files

http://rapidshare.com/files/3254109090/utorrent3.zip

don't forget to create downloads at BOXEE usb root and you cant restart the boxee during download, then you restart all progress will be lost but I'm sure everything will work fine, I just haven't the time at the moment to fix everything

**Comment by moiristo** [comment]
Thanks, got it up and running! I found out that the webui has been improved separately over the years. The cool thing about this is that RSS feed support was added to the interface, allowing you to load torrent feeds and downloading them directly. I'll try to create a pull request this weekend.

**Comment by diff3** [comment]
Nice :)

Some known bugs
- cant start download reboot and resume download (dat file error)
- cant mix lib files for utorrent with others, programs like ps will break then. I zipped every lib file i had on the box, belive you can remove some.
- trubble to load dat files created by webinterface, whats why i delete them

/
Mape0661

6 dec 2012 kl. 09:29 skrev Reinier de Lange notifications@github.com:

**Comment by diff3** [comment]
I did some tweeking, I belive I got resume to work now, 

http://rapidshare.com/files/3254109090/utorrent3.zip

Removed some files and rewrote the start script.

**Comment by moiristo** [comment]
See cb85bca1611aa02a322a2784b5ffb95b23639aee. Feel free to make modifications; I couldn't reproduce the resume issues you were talking about, so I decided not to include the chmods for now.

**Comment by youngchul76** [comment]
Hi mape0661 and moiristo,

I was almost ready to defect to wdtv live with wdlxtv to download torrent direct to my attached USB then I came across this.  

I'm not sure if this is simple to do, but could you please spare a couple of minutes for a newbie like me to install this?  I have installed the boxee plus and downloaded those files above from 4shared website, but don't have any further knowledge how to access the machine's root or how to install this torrent.  Is there some kind of manual that's floating around?

**Comment by diff3** [comment]
Hi, 

not sure if there is a manual but, ftp and telnet parts of FAQ are intresting for you

https://github.com/boxeehacks/boxeehack/wiki/FAQ

You need putty.exe from http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html
and Filezilla client from http://filezilla-project.org/download.php?type=client

you can also use any folder in windows and write ftp://[boxee-ip] in the adressbar if you dont want to use filezilla.

upload torrent.zip or torrent2.zip to /data/hack

How to useg putty: http://www.lunarc.lu.se/Support/Tutorials/TutorialPuTTY

Basic shell commands: http://www.ks.uiuc.edu/Training/Tutorials/Reference/unixprimer.html

how to use nano: http://www.debianadmin.com/nano-editor-tutorials.html

Use putty to log into boxee box remember to change to telnet and port 2323

if you never used linux before, take your time and learn the basic shell commands. 

default password is: secret

run unzip torrent.zip or unzip torrent2.zip to unzip the files

sh utorrent.sh (start for this session, will not start on boot)

or add at the end of the boot.sh file with the text editor nano. 

nano boot.sh
sh utorrent.sh &

you find torrent client at http://[boxee-ip]:1050/gui with your webbrowser. I hope you can follow this fast written text. 

Mape

**Comment by langluc** [comment]
why?

# sh utorrent.sh

mkdir: cannot create directory '/media/BOXEE/downloads': No such file or directory
chmod: /media/BOXEE/downloads: No such file or directory
utorrent.sh: line 28: syntax error: end of file unexpected (expecting "fi")

**Comment by diff3** [comment]
is your USB named BOXEE?

**Comment by langluc** [comment]
no. i try to name boxee

**Comment by diff3** [comment]
I check the files, of you also add fi to the end of the file, it will work. I updated zip file as well.

**Comment by langluc** [comment]
Folder not found. on rapidshare. Can you upload on dropbox?

**Comment by hessius** [comment]
What's the license for utorrent?
Maybe you could host it on github instead, to allow modification. You could just fork this project and add it. That way you could make a pull request into this project

**Comment by moiristo** [comment]
anyone seen my commit?

**Comment by langluc** [comment]
I see. Tomorrow i can retry with the new utorrent2.zip

**Comment by youngchul76** [comment]
Hi mape0661,

Thank you SO MUCH for your help.

I got to the same part where langluc got stuck, then after I named the hard drive to "BOXEE" I'm still getting the 
"utorrent.sh: line 28:syntax error: end of file unexpected (expecting "fi")"

Could you please help me with this one last bit...?

And then if it works, then all I have to do after that is type 
http://192.168.254.2:1050/gui
as my boxee ip is 192.168.254.2

Is that sort of right?

I CAN'T WAIT TO SEE THIS THING ACTUALLY WORK!  THIS IS GOING TO BE BETTER THAN ANY OTHER CHRISTMAS PRESENT FOR ME!  :):)

**Comment by langluc** [comment]
![Immagine](https://f.cloud.github.com/assets/3002712/22194/a753a164-49ef-11e2-9740-b52e280c4010.png)

**Comment by ribamartins** [comment]
mape0661, 
I tried installing utorrent as your explanation. It was the same problem that youngchul76 reported "utorrent.sh: line 28: syntax error: end of file unexpected (expecting" fi ")."
Added at the end of the file the word "fi" and tried to install again. Now I am getting the following error: ld-linux.so.2: Permission denied.

Could you help?

**Comment by youngchul76** [comment]
mape?

**Comment by diff3** [comment]
Added utorrent to my fork https://github.com/mape0661/boxeehack

**Comment by diff3** [comment]
youngchul76 I will update utorrent files in a few days. I have little time at the moment

**Comment by youngchul76** [comment]
Thanks mape0661, for devoting your time to help me..  I wish I could pay you!

So do I just download that boxeehack-master.zip and rehack the boxee?

**Comment by diff3** [comment]
I deleted utorrent2.zip and made a utorrent3.zip. I havent tryed it on boxee but I did try it on my debian computer with the same cataloge structure as boxee box. 

http://rapidshare.com/files/3254109090/utorrent3.zip

it's the same utorrent as in hack.zip and in my fork. only difference is that this one is standalone.

get it to boxee with a ftp program

unzip utorrent3.zip on /data/hack
chmod +x utorrent.sh

sh utorrent.sh &

to access utorrent use a webbrowser and open

http://[box-ip]:1050/gui

to stop utorrent reboot bb or

ps aux | grep utorrent | awk '{print $2}' 

kill -9 and the number(s) you got abow

And I don't need any donation, but if you wish to donate use : 

https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=daniel%40utalk%2enl&lc=US&item_name=BoxeeHacks&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted

**Comment by youngchul76** [comment]
mape,
thank you, i'm nearly there..  the only thing remaing now, and i'm quite embarrased to have to ask you this..
but when i type http://192.168.254.2:1050/gui
it says "The server 192.168.254.2:1050 requires a username and a password.  The server says: uTorrent"

What would I type in username and password...?

**Comment by diff3** [comment]
Sorry i forgot, 

User: admin
Pass: admin

**Comment by youngchul76** [comment]
Whoa!

That was the quickest forum reply I have ever received in my entire life.

**Comment by diff3** [comment]
Hehe

**Comment by youngchul76** [comment]
oh mape....
oh 
oh
oh...
I can't believe it ....
It is ....

WORKING!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Date: Fri, 21 Dec 2012 04:15:02 -0800

**Comment by diff3** [comment]
Great!

**Comment by ribamartins** [comment]
Thank you so much, mape0661.
Works fine!

**Comment by youngchul76** [comment]
umm... one last thing..  
it says in the setting that it's being saved in boxee/download, and it is there when i check the network group in boxee's system folder, but i thought it was supposed to save the torrents to attached USB disk?...

**Comment by langluc** [comment]
IT'S WORK! GREAT
The Only problem it's that i can't access to my hard disk (BOXEE) connected to BoxeeBox from my Pc. The error is Can not find username
![Immagine](https://f.cloud.github.com/assets/3002712/27192/3c22967a-4b7a-11e2-890f-13269b538d13.png)

**Comment by diff3** [comment]
Its saves to /media/BOXEE/downloads

BOXEE is the usb drive. What does the config file say? copy and past cat /data/hack/utorrent/utserver.conf

21 dec 2012 kl. 14:59 skrev youngchul76 notifications@github.com:

**Comment by diff3** [comment]
Hmm 

Check boxee settings / network for smb password. But your bb is shared under intelce. Which version of boxee hack do you use? 

21 dec 2012 kl. 15:26 skrev Luca notifications@github.com:

**Comment by langluc** [comment]
it's possible to restart automatically utorrent when i start BB? 
Now i use PUTTY and write sh utorrent.sh &.

**Comment by langluc** [comment]
Someone can upload the file boot.sh modified: add at the end of the boot.sh file with the text editor nano "sh utorrent.sh &"
I don't have linux
please

**Comment by diff3** [comment]
http://rapidshare.com/files/2769626873/boot.sh

dont forget to do a chmod +x boot.sh from PUTTY

or Boxee will fail to boot.

**Comment by langluc** [comment]
i'll do a chmod +x boot.sh from PUTTY only the first time?
1) copy the new boot.sh to data/hack
2) to do a chmod +x boot.sh from PUTTY

**Comment by diff3** [comment]
You need to do a chmod after you copy the new boot.sh to the device

21 dec 2012 kl. 23:33 skrev Luca notifications@github.com:

**Comment by langluc** [comment]
Hmm

Check boxee settings / network for smb password. But your bb is shared under intelce. Which version of boxee hack do you use?

I use 1.3.5 BB+

**Comment by boxeehacks** [comment]
Moved to #144
