### ISSUE TITLE
Migrate to plugin structure?

### ISSUE THREAD

**Issue by hessius** [boxeehacks/boxeehack#96]
Thinking out loud here:

So many feature requests and so many features actually being incorporated is great but might affect performance and might in the end be difficult to manage in the long run.

Maybe some sort of plugin system would be preferential. Users could opt-in for new or custom features and hackers and tweakers might not need to rely on getting their pull request into the main fork/branch for their features to reach the end users. Popular features might still be incorporated while resource hogs or features with a smaller audience might stay plugins.

Right now this is all working flawlessly, this is just me thinking about the long run.

**Comment by boxeehacks** [comment]
The difficulty is that for the skin modifications it's all part of the same set of files... so it'll be quite tricky to setup a plugin system for that. However something like that is exactly what I'd like to do for things like the webserver mod, torrent clients, etc. etc. stuff that runs under the hood.

**Comment by boxeehacks** [comment]
In version 1.4.0 a simple plugin system is added:
https://github.com/boxeehacks/boxeehack/wiki/Plugins
