### ISSUE TITLE
Allow for chosen app to be launched at startup

### ISSUE THREAD

**Issue by SiIason** [boxeehacks/boxeehack#99]
My sons boxee spends 90% in youtube app, my bedroom box spends 90% in slingplayer app, my sitting room box is a bit more random but generally in the slingbox app.

Would be nice in the morning to just press the remote and have boxee startup straight onto 'TV' (ie. slingbox) just like a real TV; while I get the kettle on...

**Comment by boxeehacks** [comment]
Going to add stuff to link to apps directly on the home screen. I think that takes away the need for this for most people. I don't want to change the core of what the Boxee Box is too much by making it in essence a one-app device.
